@DOC_TITLE@
Xmega Application Note
twi_master_driver.h File Reference
XMEGA TWI master driver header file.
#include "avr_compiler.h"
Data Structures
struct TWI_Master
TWI master driver struct.
Defines
#define TWI_BAUD(F_SYS, F_TWI) ((F_SYS / (2 * F_TWI)) - 5)
#define TWIM_READ_BUFFER_SIZE 8
#define TWIM_STATUS_BUSY 1
#define TWIM_STATUS_READY 0
#define TWIM_WRITE_BUFFER_SIZE 8
Typedefs
typedef struct TWI_Master TWI_Master_t
TWI master driver struct.
typedef enum TWIM_RESULT_enum TWIM_RESULT_t
Enumerations
enum TWIM_RESULT_enum {
TWIM_RESULT_UNKNOWN = (0x00<<0), TWIM_RESULT_OK = (0x01<<0), TWIM_RESULT_BUFFER_OVERFLOW = (0x02<<0), TWIM_RESULT_ARBITRATION_LOST = (0x03<<0),
TWIM_RESULT_BUS_ERROR = (0x04<<0), TWIM_RESULT_NACK_RECEIVED = (0x05<<0), TWIM_RESULT_FAIL = (0x06<<0)
}
Functions
void TWI_MasterArbitrationLostBusErrorHandler (TWI_Master_t *twi)
TWI master arbitration lost and bus error interrupt handler.
void TWI_MasterInit (TWI_Master_t *twi, TWI_t *module, TWI_MASTER_INTLVL_t intLevel, uint8_t baudRateRegisterSetting)
Initialize the TWI module.
void TWI_MasterInterruptHandler (TWI_Master_t *twi)
Common TWI master interrupt service routine.
bool TWI_MasterRead (TWI_Master_t *twi, uint8_t address, uint8_t bytesToRead)
TWI read transaction.
void TWI_MasterReadHandler (TWI_Master_t *twi)
TWI master read interrupt handler.
bool TWI_MasterReady (TWI_Master_t *twi)
Returns true if transaction is ready.
TWI_MASTER_BUSSTATE_t TWI_MasterState (TWI_Master_t *twi)
Returns the TWI bus state.
void TWI_MasterTransactionFinished (TWI_Master_t *twi, uint8_t result)
TWI transaction finished handler.
bool TWI_MasterWrite (TWI_Master_t *twi, uint8_t address, uint8_t *writeData, uint8_t bytesToWrite)
TWI write transaction.
void TWI_MasterWriteHandler (TWI_Master_t *twi)
TWI master write interrupt handler.
bool TWI_MasterWriteRead (TWI_Master_t *twi, uint8_t address, uint8_t *writeData, uint8_t bytesToWrite, uint8_t bytesToRead)
TWI write and/or read transaction.
Detailed Description
XMEGA TWI master driver header file.
This file contains the function prototypes and enumerator definitions for various configuration parameters for the XMEGA TWI master driver.
The driver is not intended for size and/or speed critical code, since most functions are just a few lines of code, and the function call overhead would decrease code performance. The driver is intended for rapid prototyping and documentation purposes for getting started with the XMEGA TWI master module.
For size and/or speed critical code, it is recommended to copy the function contents directly into your application instead of making a function call.
Application note:
AVR1308: Using the XMEGA TWI
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
1569
Date
2008-04-22 13:03:43 +0200 (ti, 22 apr 2008)
Copyright (c) 2008, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file twi_master_driver.h.
Define Documentation
#define TWI_BAUD (F_SYS, F_TWI) ((F_SYS / (2 * F_TWI)) - 5)
Baud register setting calculation. Formula described in datasheet.
Definition at line 65 of file twi_master_driver.h.
#define TWIM_READ_BUFFER_SIZE 8
Definition at line 86 of file twi_master_driver.h.
Referenced by TWI_MasterReadHandler(), and TWI_MasterWriteRead().
#define TWIM_STATUS_BUSY 1
Definition at line 70 of file twi_master_driver.h.
Referenced by TWI_MasterWriteRead().
#define TWIM_STATUS_READY 0
Transaction status defines.
Definition at line 69 of file twi_master_driver.h.
Referenced by main(), TWI_MasterArbitrationLostBusErrorHandler(), TWI_MasterReady(), TWI_MasterTransactionFinished(), TWI_MasterWriteHandler(), and TWI_MasterWriteRead().
#define TWIM_WRITE_BUFFER_SIZE 8
Buffer size defines
Definition at line 85 of file twi_master_driver.h.
Referenced by TWI_MasterWriteRead().
Typedef Documentation
typedef struct TWI_Master TWI_Master_t
TWI master driver struct.
TWI master struct. Holds pointer to TWI module, buffers and necessary varibles.
typedef enum TWIM_RESULT_enum TWIM_RESULT_t
Transaction result enumeration.
Enumeration Type Documentation
enum TWIM_RESULT_enum
Transaction result enumeration.
Enumerator:
TWIM_RESULT_UNKNOWN
TWIM_RESULT_OK
TWIM_RESULT_BUFFER_OVERFLOW
TWIM_RESULT_ARBITRATION_LOST
TWIM_RESULT_BUS_ERROR
TWIM_RESULT_NACK_RECEIVED
TWIM_RESULT_FAIL
Definition at line 74 of file twi_master_driver.h.
{
        TWIM_RESULT_UNKNOWN          = (0x00<<0),
        TWIM_RESULT_OK               = (0x01<<0),
        TWIM_RESULT_BUFFER_OVERFLOW  = (0x02<<0),
        TWIM_RESULT_ARBITRATION_LOST = (0x03<<0),
        TWIM_RESULT_BUS_ERROR        = (0x04<<0),
        TWIM_RESULT_NACK_RECEIVED    = (0x05<<0),
        TWIM_RESULT_FAIL             = (0x06<<0),
} TWIM_RESULT_t;
Function Documentation
void TWI_MasterArbitrationLostBusErrorHandler (TWI_Master_t * twi)
TWI master arbitration lost and bus error interrupt handler.
Handles TWI responses to lost arbitration and bus error.
Parameters:
twi The TWI_Master_t struct instance.
Definition at line 287 of file twi_master_driver.c.
References TWI_Master::interface, TWI_Master::result, TWI_Master::status, TWIM_RESULT_ARBITRATION_LOST, TWIM_RESULT_BUS_ERROR, and TWIM_STATUS_READY.
Referenced by TWI_MasterInterruptHandler().
{
        uint8_t currentStatus = twi->interface->MASTER.STATUS;
        /* If bus error. */
        if (currentStatus & TWI_MASTER_BUSERR_bm) {
                twi->result = TWIM_RESULT_BUS_ERROR;
        }
        /* If arbitration lost. */
        else {
                twi->result = TWIM_RESULT_ARBITRATION_LOST;
        }
        /* Clear interrupt flag. */
        twi->interface->MASTER.STATUS = currentStatus | TWI_MASTER_ARBLOST_bm;
        twi->status = TWIM_STATUS_READY;
}
void TWI_MasterInit (TWI_Master_t * twi, TWI_t * module, TWI_MASTER_INTLVL_t intLevel, uint8_t baudRateRegisterSetting)
Initialize the TWI module.
TWI module initialization function. Enables master read and write interrupts. Remember to enable interrupts globally from the main application.
Parameters:
twi The TWI_Master_t struct instance.
module The TWI module to use.
intLevel Master interrupt level.
baudRateRegisterSetting The baud rate register value.
Definition at line 83 of file twi_master_driver.c.
References TWI_Master::interface.
Referenced by main().
{
        twi->interface = module;
        twi->interface->MASTER.CTRLA = intLevel |
                                       TWI_MASTER_RIEN_bm |
                                       TWI_MASTER_WIEN_bm |
                                       TWI_MASTER_ENABLE_bm;
        twi->interface->MASTER.BAUD = baudRateRegisterSetting;
        twi->interface->MASTER.STATUS = TWI_MASTER_BUSSTATE_IDLE_gc;
}
void TWI_MasterInterruptHandler (TWI_Master_t * twi)
Common TWI master interrupt service routine.
Check current status and calls the appropriate handler.
Parameters:
twi The TWI_Master_t struct instance.
Definition at line 253 of file twi_master_driver.c.
References TWI_Master::interface, TWI_MasterArbitrationLostBusErrorHandler(), TWI_MasterReadHandler(), TWI_MasterTransactionFinished(), TWI_MasterWriteHandler(), and TWIM_RESULT_FAIL.
Referenced by ISR().
{
        uint8_t currentStatus = twi->interface->MASTER.STATUS;
        /* If arbitration lost or bus error. */
        if ((currentStatus & TWI_MASTER_ARBLOST_bm) ||
            (currentStatus & TWI_MASTER_BUSERR_bm)) {
                TWI_MasterArbitrationLostBusErrorHandler(twi);
        }
        /* If master write interrupt. */
        else if (currentStatus & TWI_MASTER_WIF_bm) {
                TWI_MasterWriteHandler(twi);
        }
        /* If master read interrupt. */
        else if (currentStatus & TWI_MASTER_RIF_bm) {
                TWI_MasterReadHandler(twi);
        }
        /* If unexpected state. */
        else {
                TWI_MasterTransactionFinished(twi, TWIM_RESULT_FAIL);
        }
}
bool TWI_MasterRead (TWI_Master_t * twi, uint8_t address, uint8_t bytesToRead)
TWI read transaction.
This function is a TWI Maste wrapper for read-only transaction.
Parameters:
twi The TWI_Master_t struct instance.
address The slave address.
bytesToRead The number of bytes to read.
Return values:
true If transaction could be started.
false If transaction could not be started.
Definition at line 169 of file twi_master_driver.c.
References TWI_MasterWriteRead().
{
        bool twi_status = TWI_MasterWriteRead(twi, address, 0, 0, bytesToRead);
        return twi_status;
}
void TWI_MasterReadHandler (TWI_Master_t * twi)
TWI master read interrupt handler.
This is the master read interrupt handler that takes care of reading bytes from the TWI slave.
Parameters:
twi The TWI_Master_t struct instance.
Definition at line 356 of file twi_master_driver.c.
References TWI_Master::bytesRead, TWI_Master::bytesToRead, TWI_Master::interface, TWI_Master::readData, TWI_MasterTransactionFinished(), TWIM_READ_BUFFER_SIZE, TWIM_RESULT_BUFFER_OVERFLOW, and TWIM_RESULT_OK.
Referenced by TWI_MasterInterruptHandler().
{
        /* Fetch data if bytes to be read. */
        if (twi->bytesRead < TWIM_READ_BUFFER_SIZE) {
                uint8_t data = twi->interface->MASTER.DATA;
                twi->readData[twi->bytesRead] = data;
                twi->bytesRead++;
        }
        /* If buffer overflow, issue STOP and BUFFER_OVERFLOW condition. */
        else {
                twi->interface->MASTER.CTRLC = TWI_MASTER_CMD_STOP_gc;
                TWI_MasterTransactionFinished(twi, TWIM_RESULT_BUFFER_OVERFLOW);
        }
        /* Local variable used in if test to avoid compiler warning. */
        uint8_t bytesToRead = twi->bytesToRead;
        /* If more bytes to read, issue ACK and start a byte read. */
        if (twi->bytesRead < bytesToRead) {
                twi->interface->MASTER.CTRLC = TWI_MASTER_CMD_RECVTRANS_gc;
        }
        /* If transaction finished, issue NACK and STOP condition. */
        else {
                twi->interface->MASTER.CTRLC = TWI_MASTER_ACKACT_bm |
                                               TWI_MASTER_CMD_STOP_gc;
                TWI_MasterTransactionFinished(twi, TWIM_RESULT_OK);
        }
}
bool TWI_MasterReady (TWI_Master_t * twi)
Returns true if transaction is ready.
This function returns a boolean whether the TWI Master is ready for a new transaction.
Parameters:
twi The TWI_Master_t struct instance.
Return values:
true If transaction could be started.
false If transaction could not be started.
Definition at line 129 of file twi_master_driver.c.
References TWI_Master::status, and TWIM_STATUS_READY.
{
        bool twi_status = (twi->status & TWIM_STATUS_READY);
        return twi_status;
}
TWI_MASTER_BUSSTATE_t TWI_MasterState (TWI_Master_t * twi)
Returns the TWI bus state.
Returns the TWI bus state (type defined in device headerfile), unknown, idle, owner or busy.
Parameters:
twi The TWI_Master_t struct instance.
Return values:
TWI_MASTER_BUSSTATE_UNKNOWN_gc Bus state is unknown.
TWI_MASTER_BUSSTATE_IDLE_gc Bus state is idle.
TWI_MASTER_BUSSTATE_OWNER_gc Bus state is owned by the master.
TWI_MASTER_BUSSTATE_BUSY_gc Bus state is busy.
Definition at line 110 of file twi_master_driver.c.
References TWI_Master::interface.
{
        TWI_MASTER_BUSSTATE_t twi_status;
        twi_status = (TWI_MASTER_BUSSTATE_t) (twi->interface->MASTER.STATUS &
                                              TWI_MASTER_BUSSTATE_gm);
        return twi_status;
}
void TWI_MasterTransactionFinished (TWI_Master_t * twi, uint8_t result)
TWI transaction finished handler.
Prepares module for new transaction.
Parameters:
twi The TWI_Master_t struct instance.
result The result of the operation.
Definition at line 395 of file twi_master_driver.c.
References TWI_Master::result, TWI_Master::status, and TWIM_STATUS_READY.
Referenced by TWI_MasterInterruptHandler(), TWI_MasterReadHandler(), and TWI_MasterWriteHandler().
{
        twi->result = result;
        twi->status = TWIM_STATUS_READY;
}
bool TWI_MasterWrite (TWI_Master_t * twi, uint8_t address, uint8_t * writeData, uint8_t bytesToWrite)
TWI write transaction.
This function is TWI Master wrapper for a write-only transaction.
Parameters:
twi The TWI_Master_t struct instance.
address Slave address.
writeData Pointer to data to write.
bytesToWrite Number of data bytes to write.
Return values:
true If transaction could be started.
false If transaction could not be started.
Definition at line 148 of file twi_master_driver.c.
References TWI_MasterWriteRead().
{
        bool twi_status = TWI_MasterWriteRead(twi, address, writeData, bytesToWrite, 0);
        return twi_status;
}
void TWI_MasterWriteHandler (TWI_Master_t * twi)
TWI master write interrupt handler.
Handles TWI transactions (master write) and responses to (N)ACK.
Parameters:
twi The TWI_Master_t struct instance.
Definition at line 313 of file twi_master_driver.c.
References TWI_Master::address, TWI_Master::bytesRead, TWI_Master::bytesToRead, TWI_Master::bytesToWrite, TWI_Master::bytesWritten, TWI_Master::interface, TWI_Master::result, TWI_Master::status, TWI_MasterTransactionFinished(), TWIM_RESULT_NACK_RECEIVED, TWIM_RESULT_OK, TWIM_STATUS_READY, and TWI_Master::writeData.
Referenced by TWI_MasterInterruptHandler().
{
        /* Local variables used in if tests to avoid compiler warning. */
        uint8_t bytesToWrite  = twi->bytesToWrite;
        uint8_t bytesToRead   = twi->bytesToRead;
        /* If NOT acknowledged (NACK) by slave cancel the transaction. */
        if (twi->interface->MASTER.STATUS & TWI_MASTER_RXACK_bm) {
                twi->interface->MASTER.CTRLC = TWI_MASTER_CMD_STOP_gc;
                twi->result = TWIM_RESULT_NACK_RECEIVED;
                twi->status = TWIM_STATUS_READY;
        }
        /* If more bytes to write, send data. */
        else if (twi->bytesWritten < bytesToWrite) {
                uint8_t data = twi->writeData[twi->bytesWritten];
                twi->interface->MASTER.DATA = data;
                ++twi->bytesWritten;
        }
        /* If bytes to read, send repeated START condition + Address +
         * 'R/_W = 1'
         */
        else if (twi->bytesRead < bytesToRead) {
                uint8_t readAddress = twi->address | 0x01;
                twi->interface->MASTER.ADDR = readAddress;
        }
        /* If transaction finished, send STOP condition and set RESULT OK. */
        else {
                twi->interface->MASTER.CTRLC = TWI_MASTER_CMD_STOP_gc;
                TWI_MasterTransactionFinished(twi, TWIM_RESULT_OK);
        }
}
bool TWI_MasterWriteRead (TWI_Master_t * twi, uint8_t address, uint8_t * writeData, uint8_t bytesToWrite, uint8_t bytesToRead)
TWI write and/or read transaction.
This function is a TWI Master write and/or read transaction. The function can be used to both write and/or read bytes to/from the TWI Slave in one transaction.
Parameters:
twi The TWI_Master_t struct instance.
address The slave address.
writeData Pointer to data to write.
bytesToWrite Number of bytes to write.
bytesToRead Number of bytes to read.
Return values:
true If transaction could be started.
false If transaction could not be started.
Definition at line 193 of file twi_master_driver.c.
References TWI_Master::address, TWI_Master::bytesRead, TWI_Master::bytesToRead, TWI_Master::bytesToWrite, TWI_Master::bytesWritten, TWI_Master::interface, TWI_Master::result, TWI_Master::status, TWIM_READ_BUFFER_SIZE, TWIM_RESULT_UNKNOWN, TWIM_STATUS_BUSY, TWIM_STATUS_READY, TWIM_WRITE_BUFFER_SIZE, and TWI_Master::writeData.
Referenced by main(), TWI_MasterRead(), and TWI_MasterWrite().
{
        /*Parameter sanity check. */
        if (bytesToWrite > TWIM_WRITE_BUFFER_SIZE) {
                return false;
        }
        if (bytesToRead > TWIM_READ_BUFFER_SIZE) {
                return false;
        }
        /*Initiate transaction if bus is ready. */
        if (twi->status == TWIM_STATUS_READY) {
                twi->status = TWIM_STATUS_BUSY;
                twi->result = TWIM_RESULT_UNKNOWN;
                twi->address = address<<1;
                /* Fill write data buffer. */
                for (uint8_t bufferIndex=0; bufferIndex < bytesToWrite; bufferIndex++) {
                        twi->writeData[bufferIndex] = writeData[bufferIndex];
                }
                twi->bytesToWrite = bytesToWrite;
                twi->bytesToRead = bytesToRead;
                twi->bytesWritten = 0;
                twi->bytesRead = 0;
                /* If write command, send the START condition + Address +
                 * 'R/_W = 0'
                 */
                if (twi->bytesToWrite > 0) {
                        uint8_t writeAddress = twi->address & ~0x01;
                        twi->interface->MASTER.ADDR = writeAddress;
                }
                /* If read command, send the START condition + Address +
                 * 'R/_W = 1'
                 */
                else if (twi->bytesToRead > 0) {
                        uint8_t readAddress = twi->address | 0x01;
                        twi->interface->MASTER.ADDR = readAddress;
                }
                return true;
        } else {
                return false;
        }
}