@DOC_TITLE@
Xmega Application Note
twi_slave_driver.c File Reference
XMEGA TWI slave driver source file.
#include "twi_slave_driver.h"
Functions
void TWI_SlaveAddressMatchHandler (TWI_Slave_t *twi)
TWI address match interrupt handler.
void TWI_SlaveDataHandler (TWI_Slave_t *twi)
TWI data interrupt handler.
void TWI_SlaveInitializeDriver (TWI_Slave_t *twi, TWI_t *module, void(*processDataFunction)(void))
Initalizes TWI slave driver structure.
void TWI_SlaveInitializeModule (TWI_Slave_t *twi, uint8_t address, TWI_SLAVE_INTLVL_t intLevel)
Initialize the TWI module.
void TWI_SlaveInterruptHandler (TWI_Slave_t *twi)
Common TWI slave interrupt service routine.
void TWI_SlaveReadHandler (TWI_Slave_t *twi)
TWI slave read interrupt handler.
void TWI_SlaveStopHandler (TWI_Slave_t *twi)
TWI stop condition interrupt handler.
void TWI_SlaveTransactionFinished (TWI_Slave_t *twi, uint8_t result)
TWI transaction finished function.
void TWI_SlaveWriteHandler (TWI_Slave_t *twi)
TWI slave write interrupt handler.
Detailed Description
XMEGA TWI slave driver source file.
This file contains the function implementations the XMEGA TWI slave driver.
The driver is not intended for size and/or speed critical code, since most functions are just a few lines of code, and the function call overhead would decrease code performance. The driver is intended for rapid prototyping and documentation purposes for getting started with the XMEGA TWI slave module.
For size and/or speed critical code, it is recommended to copy the function contents directly into your application instead of making a function call.
Several functions use the following construct: "some_register = ... | (some_parameter ? SOME_BIT_bm : 0) | ..." Although the use of the ternary operator (if ? then : else) is discouraged, in some occasions the operator makes it possible to write pretty clean and neat code. In this driver, the construct is used to set or not set a configuration bit based on a boolean input parameter, such as the "some_parameter" in the example above.
Application note:
AVR1308: Using the XMEGA TWI
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
2660
Date
2009-08-11 12:28:58 +0200 (ti, 11 aug 2009)
Copyright (c) 2008, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file twi_slave_driver.c.
Function Documentation
void TWI_SlaveAddressMatchHandler (TWI_Slave_t * twi)
TWI address match interrupt handler.
Prepares TWI module for transaction when an address match occures.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 171 of file twi_slave_driver.c.
References TWI_Slave::abort, TWI_Slave::bytesReceived, TWI_Slave::bytesSent, TWI_Slave::interface, TWI_Slave::result, TWI_Slave::status, TWI_SlaveTransactionFinished(), TWIS_RESULT_ABORTED, TWIS_RESULT_UNKNOWN, and TWIS_STATUS_BUSY.
Referenced by TWI_SlaveInterruptHandler().
{
        /* If application signalling need to abort (error occured). */
        if (twi->abort) {
                twi->interface->SLAVE.CTRLB = TWI_SLAVE_CMD_COMPTRANS_gc;
                TWI_SlaveTransactionFinished(twi, TWIS_RESULT_ABORTED);
                twi->abort = false;
        } else {
                twi->status = TWIS_STATUS_BUSY;
                twi->result = TWIS_RESULT_UNKNOWN;
                /* Disable stop interrupt. */
                uint8_t currentCtrlA = twi->interface->SLAVE.CTRLA;
                twi->interface->SLAVE.CTRLA = currentCtrlA & ~TWI_SLAVE_PIEN_bm;
                twi->bytesReceived = 0;
                twi->bytesSent = 0;
                /* Send ACK, wait for data interrupt. */
                twi->interface->SLAVE.CTRLB = TWI_SLAVE_CMD_RESPONSE_gc;
        }
}
void TWI_SlaveDataHandler (TWI_Slave_t * twi)
TWI data interrupt handler.
Calls the appropriate slave read or write handler.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 220 of file twi_slave_driver.c.
References TWI_Slave::interface, TWI_SlaveReadHandler(), and TWI_SlaveWriteHandler().
Referenced by TWI_SlaveInterruptHandler().
{
        if (twi->interface->SLAVE.STATUS & TWI_SLAVE_DIR_bm) {
                TWI_SlaveWriteHandler(twi);
        } else {
                TWI_SlaveReadHandler(twi);
        }
}
void TWI_SlaveInitializeDriver (TWI_Slave_t * twi, TWI_t * module, void(*)(void) processDataFunction)
Initalizes TWI slave driver structure.
Initialize the instance of the TWI Slave and set the appropriate values.
Parameters:
twi The TWI_Slave_t struct instance.
module Pointer to the TWI module.
processDataFunction Pointer to the function that handles incoming data.
Definition at line 80 of file twi_slave_driver.c.
References TWI_Slave::abort, TWI_Slave::bytesReceived, TWI_Slave::bytesSent, TWI_Slave::interface, TWI_Slave::Process_Data, TWI_Slave::result, TWI_Slave::status, TWIS_RESULT_UNKNOWN, and TWIS_STATUS_READY.
Referenced by main().
{
        twi->interface = module;
        twi->Process_Data = processDataFunction;
        twi->bytesReceived = 0;
        twi->bytesSent = 0;
        twi->status = TWIS_STATUS_READY;
        twi->result = TWIS_RESULT_UNKNOWN;
        twi->abort = false;
}
void TWI_SlaveInitializeModule (TWI_Slave_t * twi, uint8_t address, TWI_SLAVE_INTLVL_t intLevel)
Initialize the TWI module.
Enables interrupts on address recognition and data available. Remember to enable interrupts globally from the main application.
Parameters:
twi The TWI_Slave_t struct instance.
address Slave address for this module.
intLevel Interrupt level for the TWI slave interrupt handler.
Definition at line 103 of file twi_slave_driver.c.
References TWI_Slave::interface.
Referenced by main().
{
        twi->interface->SLAVE.CTRLA = intLevel |
                                      TWI_SLAVE_DIEN_bm |
                                      TWI_SLAVE_APIEN_bm |
                                      TWI_SLAVE_ENABLE_bm;
        twi->interface->SLAVE.ADDR = (address<<1);
}
void TWI_SlaveInterruptHandler (TWI_Slave_t * twi)
Common TWI slave interrupt service routine.
Handles all TWI transactions and responses to address match, data reception, data transmission, bus error and data collision.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 122 of file twi_slave_driver.c.
References TWI_Slave::bytesReceived, TWI_Slave::bytesSent, TWI_Slave::interface, TWI_Slave::result, TWI_Slave::status, TWI_SlaveAddressMatchHandler(), TWI_SlaveDataHandler(), TWI_SlaveStopHandler(), TWI_SlaveTransactionFinished(), TWIS_RESULT_BUS_ERROR, TWIS_RESULT_FAIL, TWIS_RESULT_TRANSMIT_COLLISION, and TWIS_STATUS_READY.
Referenced by ISR().
{
        uint8_t currentStatus = twi->interface->SLAVE.STATUS;
        /* If bus error. */
        if (currentStatus & TWI_SLAVE_BUSERR_bm) {
                twi->bytesReceived = 0;
                twi->bytesSent = 0;
                twi->result = TWIS_RESULT_BUS_ERROR;
                twi->status = TWIS_STATUS_READY;
        }
        /* If transmit collision. */
        else if (currentStatus & TWI_SLAVE_COLL_bm) {
                twi->bytesReceived = 0;
                twi->bytesSent = 0;
                twi->result = TWIS_RESULT_TRANSMIT_COLLISION;
                twi->status = TWIS_STATUS_READY;
        }
        /* If address match. */
        else if ((currentStatus & TWI_SLAVE_APIF_bm) &&
                (currentStatus & TWI_SLAVE_AP_bm)) {
                TWI_SlaveAddressMatchHandler(twi);
        }
        /* If stop (only enabled through slave read transaction). */
        else if (currentStatus & TWI_SLAVE_APIF_bm) {
                TWI_SlaveStopHandler(twi);
        }
        /* If data interrupt. */
        else if (currentStatus & TWI_SLAVE_DIF_bm) {
                TWI_SlaveDataHandler(twi);
        }
        /* If unexpected state. */
        else {
                TWI_SlaveTransactionFinished(twi, TWIS_RESULT_FAIL);
        }
}
void TWI_SlaveReadHandler (TWI_Slave_t * twi)
TWI slave read interrupt handler.
Handles TWI slave read transactions and responses.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 236 of file twi_slave_driver.c.
References TWI_Slave::abort, TWI_Slave::bytesReceived, TWI_Slave::interface, TWI_Slave::Process_Data, TWI_Slave::receivedData, TWI_SlaveTransactionFinished(), TWIS_RECEIVE_BUFFER_SIZE, TWIS_RESULT_ABORTED, and TWIS_RESULT_BUFFER_OVERFLOW.
Referenced by TWI_SlaveDataHandler().
{
        /* Enable stop interrupt. */
        uint8_t currentCtrlA = twi->interface->SLAVE.CTRLA;
        twi->interface->SLAVE.CTRLA = currentCtrlA | TWI_SLAVE_PIEN_bm;
        /* If free space in buffer. */
        if (twi->bytesReceived < TWIS_RECEIVE_BUFFER_SIZE) {
                /* Fetch data */
                uint8_t data = twi->interface->SLAVE.DATA;
                twi->receivedData[twi->bytesReceived] = data;
                /* Process data. */
                twi->Process_Data();
                twi->bytesReceived++;
                /* If application signalling need to abort (error occured),
                 * complete transaction and wait for next START. Otherwise
                 * send ACK and wait for data interrupt.
                 */
                if (twi->abort) {
                        twi->interface->SLAVE.CTRLB = TWI_SLAVE_CMD_COMPTRANS_gc;
                        TWI_SlaveTransactionFinished(twi, TWIS_RESULT_ABORTED);
                        twi->abort = false;
                } else {
                        twi->interface->SLAVE.CTRLB = TWI_SLAVE_CMD_RESPONSE_gc;
                }
        }
        /* If buffer overflow, send NACK and wait for next START. Set
         * result buffer overflow.
         */
        else {
                twi->interface->SLAVE.CTRLB = TWI_SLAVE_ACKACT_bm |
                                              TWI_SLAVE_CMD_COMPTRANS_gc;
                TWI_SlaveTransactionFinished(twi, TWIS_RESULT_BUFFER_OVERFLOW);
        }
}
void TWI_SlaveStopHandler (TWI_Slave_t * twi)
TWI stop condition interrupt handler.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 199 of file twi_slave_driver.c.
References TWI_Slave::interface, TWI_SlaveTransactionFinished(), and TWIS_RESULT_OK.
Referenced by TWI_SlaveInterruptHandler().
{
        /* Disable stop interrupt. */
        uint8_t currentCtrlA = twi->interface->SLAVE.CTRLA;
        twi->interface->SLAVE.CTRLA = currentCtrlA & ~TWI_SLAVE_PIEN_bm;
        /* Clear APIF, according to flowchart don't ACK or NACK */
        uint8_t currentStatus = twi->interface->SLAVE.STATUS;
        twi->interface->SLAVE.STATUS = currentStatus | TWI_SLAVE_APIF_bm;
        TWI_SlaveTransactionFinished(twi, TWIS_RESULT_OK);
}
void TWI_SlaveTransactionFinished (TWI_Slave_t * twi, uint8_t result)
TWI transaction finished function.
Prepares module for new transaction.
Parameters:
twi The TWI_Slave_t struct instance.
result The result of the transaction.
Definition at line 317 of file twi_slave_driver.c.
References TWI_Slave::result, TWI_Slave::status, and TWIS_STATUS_READY.
Referenced by TWI_SlaveAddressMatchHandler(), TWI_SlaveInterruptHandler(), TWI_SlaveReadHandler(), TWI_SlaveStopHandler(), and TWI_SlaveWriteHandler().
{
        twi->result = result;
        twi->status = TWIS_STATUS_READY;
}
void TWI_SlaveWriteHandler (TWI_Slave_t * twi)
TWI slave write interrupt handler.
Handles TWI slave write transactions and responses.
Parameters:
twi The TWI_Slave_t struct instance.
Definition at line 282 of file twi_slave_driver.c.
References TWI_Slave::bytesSent, TWI_Slave::interface, TWI_Slave::sendData, TWI_SlaveTransactionFinished(), TWIS_RESULT_BUFFER_OVERFLOW, TWIS_RESULT_OK, and TWIS_SEND_BUFFER_SIZE.
Referenced by TWI_SlaveDataHandler().
{
        /* If NACK, slave write transaction finished. */
        if ((twi->bytesSent > 0) && (twi->interface->SLAVE.STATUS &
                                     TWI_SLAVE_RXACK_bm)) {
                twi->interface->SLAVE.CTRLB = TWI_SLAVE_CMD_COMPTRANS_gc;
                TWI_SlaveTransactionFinished(twi, TWIS_RESULT_OK);
        }
        /* If ACK, master expects more data. */
        else {
                if (twi->bytesSent < TWIS_SEND_BUFFER_SIZE) {
                        uint8_t data = twi->sendData[twi->bytesSent];
                        twi->interface->SLAVE.DATA = data;
                        twi->bytesSent++;
                        /* Send data, wait for data interrupt. */
                        twi->interface->SLAVE.CTRLB = TWI_SLAVE_CMD_RESPONSE_gc;
                }
                /* If buffer overflow. */
                else {
                        twi->interface->SLAVE.CTRLB = TWI_SLAVE_CMD_COMPTRANS_gc;
                        TWI_SlaveTransactionFinished(twi, TWIS_RESULT_BUFFER_OVERFLOW);
                }
        }
}