@DOC_TITLE@
Xmega Application Note
usart_driver.c File Reference
Detailed Description
XMEGA USART driver source file.
This file contains the function implementations the XMEGA interrupt and polled USART driver.
The driver is not intended for size and/or speed critical code, since most functions are just a few lines of code, and the function call overhead would decrease code performance. The driver is intended for rapid prototyping and documentation purposes for getting started with the XMEGA ADC module.
For size and/or speed critical code, it is recommended to copy the function contents directly into your application instead of making a function call.
Some functions use the following construct: "some_register = ... | (some_parameter ? SOME_BIT_bm : 0) | ..." Although the use of the ternary operator (if ? then : else) is discouraged, in some occasions the operator makes it possible to write pretty clean and neat code. In this driver, the construct is used to set or not set a configuration bit based on a boolean input parameter, such as the "some_parameter" in the example above.
Application note:
AVR1307: Using the XMEGA USART
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
1694
Date
2008-07-29 14:21:58 +0200 (ti, 29 jul 2008)
Copyright (c) 2008, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file usart_driver.c.
#include "usart_driver.h"
Functions
void USART_DataRegEmpty (USART_data_t *usart_data)
Data Register Empty Interrupt Service Routine.
void USART_InterruptDriver_DreInterruptLevel_Set (USART_data_t *usart_data, USART_DREINTLVL_t dreIntLevel)
Set USART DRE interrupt level.
void USART_InterruptDriver_Initialize (USART_data_t *usart_data, USART_t *usart, USART_DREINTLVL_t dreIntLevel)
Initializes buffer and selects what USART module to use.
uint16_t USART_NineBits_GetChar (USART_t *usart)
Get received data (9 bit character).
void USART_NineBits_PutChar (USART_t *usart, uint16_t data)
Put data (9 bit character).
uint8_t USART_RXBuffer_GetByte (USART_data_t *usart_data)
Get received data (5-8 bit character).
bool USART_RXBufferData_Available (USART_data_t *usart_data)
Test if there is data in the receive software buffer.
bool USART_RXComplete (USART_data_t *usart_data)
RX Complete Interrupt Service Routine.
bool USART_TXBuffer_FreeSpace (USART_data_t *usart_data)
Test if there is data in the transmitter software buffer.
bool USART_TXBuffer_PutByte (USART_data_t *usart_data, uint8_t data)
Put data (5-8 bit character).
Function Documentation
void USART_DataRegEmpty (USART_data_t * usart_data)
Data Register Empty Interrupt Service Routine.
Data Register Empty Interrupt Service Routine. Transmits one byte from TX software buffer. Disables DRE interrupt if buffer is empty. Argument is pointer to USART (USART_data_t).
Parameters:
usart_data The USART_data_t struct instance.
Definition at line 260 of file usart_driver.c.
References Usart_and_buffer::buffer, USART_Buffer::TX, USART_Buffer::TX_Head, USART_Buffer::TX_Tail, Usart_and_buffer::usart, and USART_TX_BUFFER_MASK.
Referenced by ISR().
{
        USART_Buffer_t * bufPtr;
        bufPtr = &usart_data->buffer;
        /* Check if all data is transmitted. */
        uint8_t tempTX_Tail = usart_data->buffer.TX_Tail;
        if (bufPtr->TX_Head == tempTX_Tail){
            /* Disable DRE interrupts. */
                uint8_t tempCTRLA = usart_data->usart->CTRLA;
                tempCTRLA = (tempCTRLA & ~USART_DREINTLVL_gm) | USART_DREINTLVL_OFF_gc;
                usart_data->usart->CTRLA = tempCTRLA;
        }else{
                /* Start transmitting. */
                uint8_t data = bufPtr->TX[usart_data->buffer.TX_Tail];
                usart_data->usart->DATA = data;
                /* Advance buffer tail. */
                bufPtr->TX_Tail = (bufPtr->TX_Tail + 1) & USART_TX_BUFFER_MASK;
        }
}
void USART_InterruptDriver_DreInterruptLevel_Set (USART_data_t * usart_data, USART_DREINTLVL_t dreIntLevel)
Set USART DRE interrupt level.
Set the interrupt level on Data Register interrupt.
Note:
Changing the DRE interrupt level in the interrupt driver while it is running will not change the DRE interrupt level in the USART before the DRE interrupt have been disabled and enabled again.
Parameters:
usart_data The USART_data_t struct instance
dreIntLevel Interrupt level of the DRE interrupt.
Definition at line 106 of file usart_driver.c.
References Usart_and_buffer::dreIntLevel.
{
        usart_data->dreIntLevel = dreIntLevel;
}
void USART_InterruptDriver_Initialize (USART_data_t * usart_data, USART_t * usart, USART_DREINTLVL_t dreIntLevel)
Initializes buffer and selects what USART module to use.
Initializes receive and transmit buffer and selects what USART module to use, and stores the data register empty interrupt level.
Parameters:
usart_data The USART_data_t struct instance.
usart The USART module.
dreIntLevel Data register empty interrupt level.
Definition at line 81 of file usart_driver.c.
References Usart_and_buffer::buffer, Usart_and_buffer::dreIntLevel, USART_Buffer::RX_Head, USART_Buffer::RX_Tail, USART_Buffer::TX_Head, USART_Buffer::TX_Tail, and Usart_and_buffer::usart.
Referenced by main().
{
        usart_data->usart = usart;
        usart_data->dreIntLevel = dreIntLevel;
        usart_data->buffer.RX_Tail = 0;
        usart_data->buffer.RX_Head = 0;
        usart_data->buffer.TX_Tail = 0;
        usart_data->buffer.TX_Head = 0;
}
uint16_t USART_NineBits_GetChar (USART_t * usart)
Get received data (9 bit character).
This function reads out the received 9 bit character (uint16_t). Use the function USART_IsRXComplete to check if anything is received.
Parameters:
usart The USART module.
Return values:
Received data.
Definition at line 313 of file usart_driver.c.
{
        if(usart->CTRLB & USART_RXB8_bm) {
                return(0x0100 | usart->DATA);
        }else {
                return(usart->DATA);
        }
}
void USART_NineBits_PutChar (USART_t * usart, uint16_t data)
Put data (9 bit character).
Use the function USART_IsTXDataRegisterEmpty before using this function to put 9 bit character to the TX register.
Parameters:
usart The USART module.
data The data to send.
Definition at line 292 of file usart_driver.c.
{
        if(data & 0x0100) {
                usart->CTRLB |= USART_TXB8_bm;
        }else {
                usart->CTRLB &= ~USART_TXB8_bm;
        }
        usart->DATA = (data & 0x00FF);
}
uint8_t USART_RXBuffer_GetByte (USART_data_t * usart_data)
Get received data (5-8 bit character).
The function USART_RXBufferData_Available should be used before this function is used to ensure that data is available.
Returns data from RX software buffer.
Parameters:
usart_data The USART_data_t struct instance.
Returns:
Received data.
Definition at line 204 of file usart_driver.c.
References Usart_and_buffer::buffer, USART_Buffer::RX, USART_Buffer::RX_Tail, and USART_RX_BUFFER_MASK.
Referenced by main().
{
        USART_Buffer_t * bufPtr;
        uint8_t ans;
        bufPtr = &usart_data->buffer;
        ans = (bufPtr->RX[bufPtr->RX_Tail]);
        /* Advance buffer tail. */
        bufPtr->RX_Tail = (bufPtr->RX_Tail + 1) & USART_RX_BUFFER_MASK;
        return ans;
}
bool USART_RXBufferData_Available (USART_data_t * usart_data)
Test if there is data in the receive software buffer.
This function can be used to test if there is data in the receive software buffer.
Parameters:
usart_data The USART_data_t struct instance
Return values:
true There is data in the receive buffer.
false The receive buffer is empty.
Definition at line 181 of file usart_driver.c.
References Usart_and_buffer::buffer, USART_Buffer::RX_Head, and USART_Buffer::RX_Tail.
Referenced by main().
{
        /* Make copies to make sure that volatile access is specified. */
        uint8_t tempHead = usart_data->buffer.RX_Head;
        uint8_t tempTail = usart_data->buffer.RX_Tail;
        /* There are data left in the buffer unless Head and Tail are equal. */
        return (tempHead != tempTail);
}
bool USART_RXComplete (USART_data_t * usart_data)
RX Complete Interrupt Service Routine.
RX Complete Interrupt Service Routine. Stores received data in RX software buffer.
Parameters:
usart_data The USART_data_t struct instance.
Definition at line 227 of file usart_driver.c.
References Usart_and_buffer::buffer, USART_Buffer::RX, USART_Buffer::RX_Head, USART_Buffer::RX_Tail, Usart_and_buffer::usart, and USART_RX_BUFFER_MASK.
Referenced by ISR().
{
        USART_Buffer_t * bufPtr;
        bool ans;
        bufPtr = &usart_data->buffer;
        /* Advance buffer head. */
        uint8_t tempRX_Head = (bufPtr->RX_Head + 1) & USART_RX_BUFFER_MASK;
        /* Check for overflow. */
        uint8_t tempRX_Tail = bufPtr->RX_Tail;
        uint8_t data = usart_data->usart->DATA;
        if (tempRX_Head == tempRX_Tail) {
                ans = false;
        }else{
                ans = true;
                usart_data->buffer.RX[usart_data->buffer.RX_Head] = data;
                usart_data->buffer.RX_Head = tempRX_Head;
        }
        return ans;
}
bool USART_TXBuffer_FreeSpace (USART_data_t * usart_data)
Test if there is data in the transmitter software buffer.
This function can be used to test if there is free space in the transmitter software buffer.
Parameters:
usart_data The USART_data_t struct instance.
Return values:
true There is data in the receive buffer.
false The receive buffer is empty.
Definition at line 123 of file usart_driver.c.
References Usart_and_buffer::buffer, USART_Buffer::TX_Head, USART_Buffer::TX_Tail, and USART_TX_BUFFER_MASK.
Referenced by USART_TXBuffer_PutByte().
{
        /* Make copies to make sure that volatile access is specified. */
        uint8_t tempHead = (usart_data->buffer.TX_Head + 1) & USART_TX_BUFFER_MASK;
        uint8_t tempTail = usart_data->buffer.TX_Tail;
        /* There are data left in the buffer unless Head and Tail are equal. */
        return (tempHead != tempTail);
}
bool USART_TXBuffer_PutByte (USART_data_t * usart_data, uint8_t data)
Put data (5-8 bit character).
Stores data byte in TX software buffer and enables DRE interrupt if there is free space in the TX software buffer.
Parameters:
usart_data The USART_data_t struct instance.
data The data to send.
Definition at line 143 of file usart_driver.c.
References Usart_and_buffer::buffer, Usart_and_buffer::dreIntLevel, USART_Buffer::TX, USART_Buffer::TX_Head, Usart_and_buffer::usart, USART_TX_BUFFER_MASK, and USART_TXBuffer_FreeSpace().
Referenced by main().
{
        uint8_t tempCTRLA;
        uint8_t tempTX_Head;
        bool TXBuffer_FreeSpace;
        USART_Buffer_t * TXbufPtr;
        TXbufPtr = &usart_data->buffer;
        TXBuffer_FreeSpace = USART_TXBuffer_FreeSpace(usart_data);
        if(TXBuffer_FreeSpace)
        {
                tempTX_Head = TXbufPtr->TX_Head;
                TXbufPtr->TX[tempTX_Head]= data;
                /* Advance buffer head. */
                TXbufPtr->TX_Head = (tempTX_Head + 1) & USART_TX_BUFFER_MASK;
                /* Enable DRE interrupt. */
                tempCTRLA = usart_data->usart->CTRLA;
                tempCTRLA = (tempCTRLA & ~USART_DREINTLVL_gm) | usart_data->dreIntLevel;
                usart_data->usart->CTRLA = tempCTRLA;
        }
        return TXBuffer_FreeSpace;
}