@DOC_TITLE@
Xmega Application Note
adc.c File Reference
AVR XMEGA Analog to Digital Converter driver.
#include <compiler.h>
#include <adc.h>
Functions
void adc_disable (ADC_t *adc)
Disable ADC.
static void adc_disable_clock (ADC_t *adc)
Disable peripheral clock for ADC.
void adc_enable (ADC_t *adc)
Enable ADC.
static void adc_enable_clock (ADC_t *adc)
Enable peripheral clock for ADC.
bool adc_is_enabled (ADC_t *adc)
Check if the ADC is enabled.
void adc_read_configuration (ADC_t *adc, struct adc_config *conf)
Read configuration from ADC module.
void adc_write_configuration (ADC_t *adc, const struct adc_config *conf)
Write configuration to ADC module.
void adcch_read_configuration (ADC_t *adc, uint8_t ch, struct adc_channel_config *ch_conf)
Read configuration from ADC channel.
void adcch_write_configuration (ADC_t *adc, uint8_t ch, const struct adc_channel_config *ch_conf)
Write configuration to ADC channel.
Detailed Description
AVR XMEGA Analog to Digital Converter driver.
Copyright (C) 2010 Atmel Corporation. All rights reserved.
Definition in file adc.c.
Function Documentation
static void adc_disable_clock (ADC_t * adc) [static]
Disable peripheral clock for ADC.
For internal use only.
Decrements the enable count for the ADC, then disables its peripheral clock if the count hit zero. If the count did not hit zero, it indicates the ADC is enabled.
Parameters:
adc Pointer to ADC module
Definition at line 244 of file adc.c.
References Assert, SYSCLK_ADC, sysclk_disable_module(), SYSCLK_PORT_A, and SYSCLK_PORT_B.
Referenced by adc_disable(), adc_read_configuration(), adc_write_configuration(), adcch_read_configuration(), and adcch_write_configuration().
{
#ifdef ADCA
        if ((uintptr_t)adc == (uintptr_t)(&ADCA)) {
                Assert(adca_enable_count);
                if (!--adca_enable_count) {
                        sysclk_disable_module(SYSCLK_PORT_A, SYSCLK_ADC);
                }
        } else
#endif
#ifdef ADCB
        if ((uintptr_t)adc == (uintptr_t)(&ADCB)) {
                Assert(adcb_enable_count);
                if (!--adcb_enable_count) {
                        sysclk_disable_module(SYSCLK_PORT_B, SYSCLK_ADC);
                }
        } else
#endif
        {
                Assert(0);
        }
}
static void adc_enable_clock (ADC_t * adc) [static]
Enable peripheral clock for ADC.
For internal use only.
Checks if the enable count for the ADC is zero, then increments it. If the count was zero, the peripheral clock is enabled. Otherwise, it is already enabled.
Parameters:
adc Pointer to ADC module.
Definition at line 209 of file adc.c.
References Assert, SYSCLK_ADC, sysclk_enable_module(), SYSCLK_PORT_A, and SYSCLK_PORT_B.
Referenced by adc_enable(), adc_read_configuration(), adc_write_configuration(), adcch_read_configuration(), and adcch_write_configuration().
{
#ifdef ADCA
        if ((uintptr_t)adc == (uintptr_t)(&ADCA)) {
                Assert(adca_enable_count < 0xff);
                if (!adca_enable_count++) {
                        sysclk_enable_module(SYSCLK_PORT_A, SYSCLK_ADC);
                }
        } else
#endif
#ifdef ADCB
        if ((uintptr_t)adc == (uintptr_t)(&ADCB)) {
                Assert(adcb_enable_count < 0xff);
                if (!adcb_enable_count++) {
                        sysclk_enable_module(SYSCLK_PORT_B, SYSCLK_ADC);
                }
        } else
#endif
        {
                Assert(0);
        }
}