@DOC_TITLE@
Xmega Application Note
ccp.h File Reference
Configuration Change Protection write functions.
Functions
void ccp_write_io (void *addr, uint8_t value)
Write to a CCP-protected 8-bit I/O register.
Detailed Description
Configuration Change Protection write functions.
Copyright (C) 2010 Atmel Corporation. All rights reserved.
Definition in file ccp.h.
Function Documentation
void ccp_write_io (void * addr, uint8_t value)
Write to a CCP-protected 8-bit I/O register.
Parameters:
addr Address of the I/O register
value Value to be written
Referenced by nvm_exec(), nvm_issue_command(), pmic_set_vector_location(), reset_do_soft_reset(), sysclk_init(), sysclk_lock(), sysclk_set_prescalers(), and sysclk_set_source().