@DOC_TITLE@
Xmega Application Note
clz_ctz.h File Reference
CLZ/CTZ C implemetation.
Defines
#define clz(x) compiler_demux_size(sizeof(x), clz, (x))
Count leading zeros in unsigned integer.
#define ctz(x) compiler_demux_size(sizeof(x), ctz, (x))
Count trailing zeros in unsigned integer.
Functions
static __always_inline uint8_t clz16 (uint16_t x)
Count leading zeros in unsigned, 16-bit integer.
static __always_inline uint8_t clz32 (uint32_t x)
Count leading zeros in unsigned, 32-bit integer.
static __always_inline uint8_t clz8 (uint8_t x)
Count leading zeros in unsigned, 8-bit integer.
static __always_inline uint8_t ctz16 (uint16_t x)
Count trailing zeros in unsigned, 16-bit integer.
static __always_inline uint8_t ctz32 (uint32_t x)
Count trailing zeros in unsigned, 32-bit integer.
static __always_inline uint8_t ctz8 (uint8_t x)
Count trailing zeros in unsigned, 8-bit integer.
Detailed Description
CLZ/CTZ C implemetation.
Copyright (C) 2009 Atmel Corporation. All rights reserved.
Definition in file clz_ctz.h.
Define Documentation
#define clz (x) compiler_demux_size(sizeof(x), clz, (x))
Count leading zeros in unsigned integer.
This macro takes unsigned integers of any size, and evaluates to a call to the clz-function for its size. These functions count the number of zeros, starting with the MSB, before a one occurs in the integer.
Parameters:
x Unsigned integer to count the leading zeros in.
Returns:
The number of leading zeros in x.
Definition at line 51 of file clz_ctz.h.
Referenced by ilog2().
#define ctz (x) compiler_demux_size(sizeof(x), ctz, (x))
Count trailing zeros in unsigned integer.
This macro takes unsigned integers of any size, and evaluates to a call to the ctz-function for its size. These functions count the number of zeros, starting with the LSB, before a one occurs in the integer.
Parameters:
x Unsigned integer to count the trailing zeros in.
Returns:
The number of trailing zeros in x.
Definition at line 138 of file clz_ctz.h.
Referenced by fifo_init_malloc(), and fifo_init_no_malloc().
Function Documentation
static __always_inline uint8_t clz16 (uint16_t x) [static]
Count leading zeros in unsigned, 16-bit integer.
For internal use only.
Parameters:
x Unsigned word to count the leading zeros in.
Returns:
The number of leading zeros in x.
Definition at line 93 of file clz_ctz.h.
References clz8().
Referenced by clz32().
{
        uint8_t bit = 0;
        if (x & 0xff00) {
                x >>= 8;
        } else {
                bit += 8;
        }
        return bit + clz8(x);
}
static __always_inline uint8_t clz32 (uint32_t x) [static]
Count leading zeros in unsigned, 32-bit integer.
For internal use only.
Parameters:
x Unsigned double word to count the leading zeros in.
Returns:
The number of leading zeros in x.
Definition at line 114 of file clz_ctz.h.
References clz16().
{
        uint8_t bit = 0;
        if (x & 0xffff0000) {
                x >>= 16;
        } else {
                bit += 16;
        }
        return bit + clz16(x);
}
static __always_inline uint8_t clz8 (uint8_t x) [static]
Count leading zeros in unsigned, 8-bit integer.
For internal use only.
Parameters:
x Unsigned byte to count the leading zeros in.
Returns:
The number of leading zeros in x.
Definition at line 61 of file clz_ctz.h.
Referenced by clz16().
{
        uint8_t bit = 0;
        if (x & 0xf0) {
                x >>= 4;
        } else {
                bit += 4;
        }
        if (x & 0x0c) {
                x >>= 2;
        } else {
                bit += 2;
        }
        if (!(x & 0x02)) {
                bit++;
        }
        return bit;
}
static __always_inline uint8_t ctz16 (uint16_t x) [static]
Count trailing zeros in unsigned, 16-bit integer.
For internal use only.
Parameters:
x Unsigned word to count the trailing zeros in.
Returns:
The number of trailing zeros in x.
Definition at line 174 of file clz_ctz.h.
References ctz8().
Referenced by ctz32().
{
        uint8_t bit = 0;
        if (!(x & 0x00ff)) {
                bit += 8;
                x >>= 8;
        }
        return bit + ctz8(x);
}
static __always_inline uint8_t ctz32 (uint32_t x) [static]
Count trailing zeros in unsigned, 32-bit integer.
For internal use only.
Parameters:
x Unsigned double word to count the trailing zeros in.
Returns:
The number of trailing zeros in x.
Definition at line 194 of file clz_ctz.h.
References ctz16().
{
        uint8_t bit = 0;
        if (!(x & 0x0000ffff)) {
                bit += 16;
                x >>= 16;
        }
        return bit + ctz16(x);
}
static __always_inline uint8_t ctz8 (uint8_t x) [static]
Count trailing zeros in unsigned, 8-bit integer.
For internal use only.
Parameters:
x Unsigned byte to count the trailing zeros in.
Returns:
The number of leading zeros in x.
Definition at line 148 of file clz_ctz.h.
Referenced by ctz16().
{
        uint8_t bit = 0;
        if (!(x & 0x0f)) {
                bit += 4;
                x >>= 4;
        }
        if (!(x & 0x03)) {
                bit += 2;
                x >>= 2;
        }
        if (!(x & 0x01))
                bit++;
        return bit;
}