@DOC_TITLE@
Xmega Application Note
fifo.c File Reference
This file controls the software FIFO management.
#include "compiler.h"
#include "fifo.h"
Functions
uint16_t fifo_get_free_size (fifo_desc_t *fifo_desc)
This function returns the remaining free spaces of the FIFO (in number of elements).
uint16_t fifo_get_used_size (fifo_desc_t *fifo_desc)
This function returns the number of elements in the FIFO.
int fifo_init_malloc (fifo_desc_t **fifo_desc, uint16_t size, uint16_t element_size)
This function initializes a new software FIFO for a certain 'size'. Both fifo descriptor and buffer are allocated by the function.
int fifo_init_no_malloc (fifo_desc_t *fifo_desc, void *buffer, uint16_t size, uint16_t element_size)
This function initializes a new software FIFO for a certain 'size'. Both fifo descriptor and buffer must be allocated by the caller before calling this function.
int fifo_pull (fifo_desc_t *fifo_desc, void *item)
This function gets a new element from the FIFO.
int fifo_push (fifo_desc_t *fifo_desc, uint32_t item)
This function pushes a new element in the FIFO.
void fifo_reset (fifo_desc_t *fifo_desc)
This function resets a software FIFO.
void fifo_stop_malloc (fifo_desc_t **fifo_desc)
This function stops a software FIFO and free the allocated buffer.
Detailed Description
This file controls the software FIFO management.
These functions allow to use FIFO thanks to simple APIs. The FIFO can be 100% full thanks to a double-index range implementation. This is particurly well suited for any kind of application needing queuing data, events, ...
Compiler: IAR EWAVR32 and GNU GCC for AVR32
Supported devices: All AVR32 devices can be used.
AppNote:
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file fifo.c.
Function Documentation
uint16_t fifo_get_free_size (fifo_desc_t * fifo_desc)
This function returns the remaining free spaces of the FIFO (in number of elements).
Parameters:
fifo_desc The FIFO descriptor.
Returns:
The number of free elements.
Definition at line 147 of file fifo.c.
References fifo_get_used_size(), and fifo_desc_t::size.
Referenced by fifo_push().
{
        return fifo_desc->size - fifo_get_used_size(fifo_desc);
}
uint16_t fifo_get_used_size (fifo_desc_t * fifo_desc)
This function returns the number of elements in the FIFO.
Parameters:
fifo_desc The FIFO descriptor.
Returns:
The number of used elements.
Definition at line 139 of file fifo.c.
References fifo_desc_t::rd_id, fifo_desc_t::size, and fifo_desc_t::wr_id.
Referenced by fifo_get_free_size(), and fifo_pull().
{
        uint16_t val;
        val = fifo_desc->wr_id + 2 * fifo_desc->size;
        val -= fifo_desc->rd_id;
        return val & ((2 * fifo_desc->size) - 1);
}
int fifo_init_malloc (fifo_desc_t ** fifo_desc, uint16_t size, uint16_t element_size)
This function initializes a new software FIFO for a certain 'size'. Both fifo descriptor and buffer are allocated by the function.
Parameters:
fifo_desc The FIFO descriptor.
size Size of the buffer (unit is in number of 'item'). It must be a 2-power.
fifo_desc The size of the element.
FIFO_ELEMENT_8BITS
FIFO_ELEMENT_16BITS
FIFO_ELEMENT_32BITS
Returns:
Status
Return values:
FIFO_OK when no error occured.
FIFO_ERROR when the buffer can not be allocated or if the size is not a 2-power.
Definition at line 84 of file fifo.c.
References ctz, FIFO_ERROR, and FIFO_OK.
{
        uint16_t tmp;
        // Check the size parameter. It must be a 2-power.
        tmp = size >> ctz(size);
        if (tmp != 1) {
                // We prefer catching this critical situation that way since most of users does not
                // even test return value...
                while (1) {
                }
                //return FIFO_ERROR;
        }
        if (!(*fifo_desc = malloc(sizeof(fifo_desc_t))))
                return FIFO_ERROR;
        // Allocate memory for the buffer.
        if (!((*fifo_desc)->buffer.u8ptr = malloc(size))) {
                free(*fifo_desc);
                return FIFO_ERROR;
        }
        // Keep the alignement
        (*fifo_desc)->align = element_size;
        // Fifo starts empty.
        (*fifo_desc)->rd_id = (*fifo_desc)->wr_id = 0;
        // Save the size parameter.
        (*fifo_desc)->size = size;
        return FIFO_OK;
}
int fifo_init_no_malloc (fifo_desc_t * fifo_desc, void * buffer, uint16_t size, uint16_t element_size)
This function initializes a new software FIFO for a certain 'size'. Both fifo descriptor and buffer must be allocated by the caller before calling this function.
Parameters:
fifo_desc Pointer on the FIFO descriptor.
buffer Pointer on the buffer.
size Size of the buffer (unit is in number of 'item'). It must be a 2-power.
fifo_desc The size of the element.
FIFO_ELEMENT_8BITS
FIFO_ELEMENT_16BITS
FIFO_ELEMENT_32BITS
Returns:
Status
Return values:
FIFO_OK when no error occured.
FIFO_ERROR when the size is not a 2-power.
Definition at line 54 of file fifo.c.
References fifo_desc_t::align, fifo_desc_t::buffer, ctz, FIFO_OK, fifo_desc_t::rd_id, fifo_desc_t::size, UnionVPtr::u8ptr, and fifo_desc_t::wr_id.
{
        uint16_t tmp;
        // Check the size parameter. It must be a 2-power.
        tmp = size >> ctz(size);
        if (tmp != 1) {
                // We prefer catching this critical situation that way since most of users does not
                // even test return value...
                while (1) {
                }
                //return FIFO_ERROR;
        }
        // Keep the alignement
        fifo_desc->align = element_size;
        // Fifo starts empty.
        fifo_desc->rd_id = fifo_desc->wr_id = 0;
        // Save the size parameter.
        fifo_desc->size = size;
        // Save the buffer pointer
        fifo_desc->buffer.u8ptr = buffer;
        return FIFO_OK;
}
int fifo_pull (fifo_desc_t * fifo_desc, void * item)
This function gets a new element from the FIFO.
Parameters:
fifo_desc The FIFO descriptor.
item extracted element.
Returns:
Status
Return values:
FIFO_OK when no error occured.
FIFO_ERROR_UNDERFLOW when the FIFO was empty.
Definition at line 173 of file fifo.c.
References fifo_desc_t::align, fifo_desc_t::buffer, FIFO_ELEMENT_16BITS, FIFO_ELEMENT_8BITS, FIFO_ERROR_UNDERFLOW, fifo_get_used_size(), FIFO_OK, fifo_desc_t::rd_id, fifo_desc_t::size, UnionVPtr::u16ptr, UnionVPtr::u32ptr, and UnionVPtr::u8ptr.
{
        uint8_t rd_id;
        if (fifo_get_used_size(fifo_desc) == 0)
                return FIFO_ERROR_UNDERFLOW;
        rd_id = fifo_desc->rd_id;
        if (fifo_desc->align == FIFO_ELEMENT_8BITS)
                *(uint8_t*) item = fifo_desc->buffer.u8ptr[rd_id & (fifo_desc->size - 1)];
        else if (fifo_desc->align == FIFO_ELEMENT_16BITS)
                *(uint16_t*) item = fifo_desc->buffer.u16ptr[rd_id
                      & (fifo_desc->size - 1)];
        else
                // if( fifo_desc->align==FIFO_ELEMENT_32BITS )
                *(uint32_t*) item = fifo_desc->buffer.u32ptr[rd_id
                      & (fifo_desc->size - 1)];
        // Must be the last thing to do.
        fifo_desc->rd_id = (rd_id + 1) & ((2 * fifo_desc->size) - 1);
        return FIFO_OK;
}
int fifo_push (fifo_desc_t * fifo_desc, uint32_t item)
This function pushes a new element in the FIFO.
Parameters:
fifo_desc The FIFO descriptor.
item element to push.
Returns:
Status
Return values:
FIFO_OK when no error occured.
FIFO_ERROR_OVERFLOW when the FIFO was already full before pushing the element.
Definition at line 152 of file fifo.c.
References fifo_desc_t::align, fifo_desc_t::buffer, FIFO_ELEMENT_16BITS, FIFO_ELEMENT_8BITS, FIFO_ERROR_OVERFLOW, fifo_get_free_size(), FIFO_OK, fifo_desc_t::size, UnionVPtr::u16ptr, UnionVPtr::u32ptr, UnionVPtr::u8ptr, and fifo_desc_t::wr_id.
{
        uint8_t wr_id;
        if (fifo_get_free_size(fifo_desc) == 0)
                return FIFO_ERROR_OVERFLOW;
        wr_id = fifo_desc->wr_id;
        if (fifo_desc->align == FIFO_ELEMENT_8BITS)
                fifo_desc->buffer.u8ptr[wr_id & (fifo_desc->size - 1)] = item;
        else if (fifo_desc->align == FIFO_ELEMENT_16BITS)
                fifo_desc->buffer.u16ptr[wr_id & (fifo_desc->size - 1)] = item;
        else
                // if( fifo_desc->align==FIFO_ELEMENT_32BITS )
                fifo_desc->buffer.u32ptr[wr_id & (fifo_desc->size - 1)] = item;
        // Must be the last thing to do.
        fifo_desc->wr_id = (wr_id + 1) & ((2 * fifo_desc->size) - 1);
        return FIFO_OK;
}
void fifo_reset (fifo_desc_t * fifo_desc)
This function resets a software FIFO.
Parameters:
fifo_desc The FIFO descriptor.
Definition at line 120 of file fifo.c.
References fifo_desc_t::rd_id, and fifo_desc_t::wr_id.
{
        // Fifo starts empty.
        fifo_desc->rd_id = fifo_desc->wr_id = 0;
}
void fifo_stop_malloc (fifo_desc_t ** fifo_desc)
This function stops a software FIFO and free the allocated buffer.
Parameters:
fifo_desc The FIFO descriptor.
Definition at line 126 of file fifo.c.
{
        // Free allocated memory
        if ((*fifo_desc)->buffer.u8ptr) {
                free((void*) (*fifo_desc)->buffer.u8ptr);
                (*fifo_desc)->buffer.u8ptr = NULL;
        }
        if (*fifo_desc) {
                free((void*) *fifo_desc);
                *fifo_desc = NULL;
        }
}