@DOC_TITLE@
Xmega Application Note
Sleep manager
Enumerations
enum sleepmgr_mode {
SLEEPMGR_ACTIVE, SLEEPMGR_IDLE, SLEEPMGR_ESTDBY, SLEEPMGR_PSAVE,
SLEEPMGR_STDBY, SLEEPMGR_PDOWN, SLEEPMGR_NR_OF_MODES
}
Sleep mode locks.
Functions
static void sleepmgr_enter_sleep (void)
Go to sleep in the deepest allowed mode.
static void sleepmgr_init (void)
Initialize the lock counts.
static void sleepmgr_lock_mode (enum sleepmgr_mode mode)
Increase lock count for a sleep mode.
static void sleepmgr_unlock_mode (enum sleepmgr_mode mode)
Decrease lock count for a sleep mode.
Detailed Description
The sleep manager is a service for ensuring that the device is not put to sleep in deeper sleep modes than the system (e.g., peripheral drivers, services or the application) allows at any given time.
It is based on the use of lock counting for the individual sleep modes, and will put the device to sleep in the shallowest sleep mode that has a non-zero lock count. The drivers/services/application can change these counts by use of sleepmgr_lock_mode and sleepmgr_unlock_mode. Refer to sleepmgr_mode for a list of the sleep modes available for locking, and the device datasheet for information on their effect.
The application must supply the file conf_sleepmgr.h.
For the sleep manager to be enabled, the symbol CONFIG_SLEEPMGR_ENABLE must be defined, e.g., in conf_sleepmgr.h. If this symbol is not defined, the functions are replaced with dummy functions and no RAM is used.
Enumeration Type Documentation
enum sleepmgr_mode
Sleep mode locks.
Identifiers for the different sleep mode locks.
Enumerator:
SLEEPMGR_ACTIVE
Active mode.
SLEEPMGR_IDLE
Idle mode.
SLEEPMGR_ESTDBY
Extended Standby mode.
SLEEPMGR_PSAVE
Power Save mode.
SLEEPMGR_STDBY
Standby mode.
SLEEPMGR_PDOWN
Power Down mode.
SLEEPMGR_NR_OF_MODES
Definition at line 53 of file sleepmgr.h.
                   {
        SLEEPMGR_ACTIVE,
        SLEEPMGR_IDLE,
        SLEEPMGR_ESTDBY,
        SLEEPMGR_PSAVE,
        SLEEPMGR_STDBY,
        SLEEPMGR_PDOWN,
        SLEEPMGR_NR_OF_MODES,
};
Function Documentation
sleepmgr_enter_sleep (void) [inline, static]
Go to sleep in the deepest allowed mode.
Searches through the sleep mode lock counts, starting at the shallowest sleep mode, until the first non-zero lock count is found. The device is then put to sleep in the sleep mode that corresponds to the lock.
Note:
This function enables interrupts before going to sleep, and will leave them enabled upon return. This also applies if sleep is skipped due to ACTIVE mode being locked.
Definition at line 89 of file sleepmgr.h.
References Assert, cpu_irq_disable, cpu_irq_enable, sleep_set_mode(), and SLEEPMGR_NR_OF_MODES.
{
#ifdef CONFIG_SLEEPMGR_ENABLE
        enum SLEEP_SMODE_enum PROGMEM_PTR_T config_ptr = sleepmgr_configs;
        enum SLEEP_SMODE_enum               config;
        uint8_t                             *lock_ptr = sleepmgr_locks;
        cpu_irq_disable();
        // Return right away if first mode (ACTIVE) is locked.
        if (*lock_ptr) {
                cpu_irq_enable();
                return;
        }
        lock_ptr++;
        // Find first non-zero lock count, starting with the shallowest modes.
        while (!(*lock_ptr)) {
                lock_ptr++;
                config_ptr++;
        }
        Assert((uintptr_t)(lock_ptr - sleepmgr_locks) < SLEEPMGR_NR_OF_MODES);
        config = PROGMEM_READ_BYTE(config_ptr);
        sleep_set_mode(config);
        sleep_enable();
        cpu_irq_enable();
        sleep_enter();
        sleep_disable();
#else
        cpu_irq_enable();
#endif /* CONFIG_SLEEPMGR_ENABLE */
}
static void sleepmgr_init (void) [inline, static]
Initialize the lock counts.
Sets all lock counts to 0, except the very last one, which is set to 1. This is done to simplify the algorithm for finding the deepest allowable sleep mode in sleepmgr_enter_sleep.
Definition at line 104 of file sleepmgr.h.
References SLEEPMGR_NR_OF_MODES.
{
#ifdef CONFIG_SLEEPMGR_ENABLE
        uint8_t i;
        for (i = 0; i < SLEEPMGR_NR_OF_MODES - 1; i++) {
                sleepmgr_locks[i] = 0;
        }
        sleepmgr_locks[SLEEPMGR_NR_OF_MODES - 1] = 1;
#endif /* CONFIG_SLEEPMGR_ENABLE */
}
static void sleepmgr_lock_mode (enum sleepmgr_mode mode) [inline, static]
Increase lock count for a sleep mode.
Increases the lock count for mode to ensure that the sleep manager does not put the device to sleep in the deeper sleep modes.
Parameters:
mode Sleep mode to lock.
Definition at line 124 of file sleepmgr.h.
References Assert, cpu_irq_restore(), and cpu_irq_save().
Referenced by adc_enable(), and rtc_init().
{
#ifdef CONFIG_SLEEPMGR_ENABLE
        irqflags_t flags;
        Assert(sleepmgr_locks[mode] < 0xff);
        // Enter a critical section
        flags = cpu_irq_save();
        ++sleepmgr_locks[mode];
        // Leave the critical section
        cpu_irq_restore(flags);
#endif /* CONFIG_SLEEPMGR_ENABLE */
}
static void sleepmgr_unlock_mode (enum sleepmgr_mode mode) [inline, static]
Decrease lock count for a sleep mode.
Decreases the lock count for mode. If the lock count reaches 0, the sleep manager can put the device to sleep in the deeper sleep modes.
Parameters:
mode Sleep mode to unlock.
Definition at line 149 of file sleepmgr.h.
References Assert, cpu_irq_restore(), and cpu_irq_save().
Referenced by adc_disable().
{
#ifdef CONFIG_SLEEPMGR_ENABLE
        irqflags_t flags;
        Assert(sleepmgr_locks[mode]);
        // Enter a critical section
        flags = cpu_irq_save();
        --sleepmgr_locks[mode];
        // Leave the critical section
        cpu_irq_restore(flags);
#endif /* CONFIG_SLEEPMGR_ENABLE */
}