@DOC_TITLE@
Xmega Application Note
Real Time Counter (RTC)
Typedefs
typedef void(* rtc_callback_t)(uint32_t time)
Callback definition for alarm callback.
Functions
bool rtc_alarm_has_triggered (void)
Check if pending alarm have triggered.
uint32_t rtc_get_time (void)
Get current time.
void rtc_init (void)
Initialize the RTC.
void rtc_set_alarm (uint32_t time)
Set alarm time.
static void rtc_set_alarm_relative (uint32_t offset)
Set alarm relative to current time.
void rtc_set_callback (rtc_callback_t callback)
Set callback to call on alarm.
void rtc_set_time (uint32_t time)
Set current time.
Detailed Description
This is a driver implementation for the XMEGA RTC.
If current time is close to a time unit roll over, there is a risk to miss this when using a value of 0.
A safe use of this can be in an alarm callback.
Typedef Documentation
typedef void(* rtc_callback_t)(uint32_t time)
Callback definition for alarm callback.
Parameters:
time The time of the alarm
Definition at line 121 of file rtc.h.
Function Documentation
bool rtc_alarm_has_triggered (void)
Check if pending alarm have triggered.
Return values:
true Alarm have triggered
false Alarm is pending
Definition at line 153 of file rtc.c.
References RTC_COMPARE_INT_LEVEL.
{
        // Interrupt enable is used on pending alarm
        return !(RTC.INTCTRL & RTC_COMPARE_INT_LEVEL);
}
uint32_t rtc_get_time (void)
Get current time.
Returns:
Current time value
Note:
Due to errate, this can return old values shortly after waking up from sleep.
Definition at line 107 of file rtc.c.
References rtc_data_struct::counter_high, cpu_irq_restore(), cpu_irq_save(), and rtc_data.
Referenced by rtc_set_alarm_relative().
{
        irqflags_t flags;
        uint16_t   count_high;
        uint16_t   count_low;
        flags = cpu_irq_save();
        count_high = rtc_data.counter_high;
        count_low = RTC.CNT;
        // Test for possible pending increase of high count value
        if ((count_low == 0) && (RTC.INTFLAGS & RTC_OVFIF_bm))
                count_high++;
        cpu_irq_restore(flags);
        return ((uint32_t)count_high << 16) | count_low;
}
void rtc_init (void)
Initialize the RTC.
Start up the RTC and start counting from 0
Definition at line 174 of file rtc.c.
References RTC_OVERFLOW_INT_LEVEL, sleepmgr_lock_mode(), SLEEPMGR_PSAVE, sysclk_enable_module(), SYSCLK_PORT_GEN, and SYSCLK_RTC.
{
        sysclk_enable_module(SYSCLK_PORT_GEN, SYSCLK_RTC);
        CLK.RTCCTRL = CONFIG_RTC_CLOCK_SOURCE | CLK_RTCEN_bm;
        RTC.PER = 0xffff;
        RTC.CNT = 0;
        /* Since overflow interrupt is needed all the time we limit sleep to
         * power-save.
         */
        sleepmgr_lock_mode(SLEEPMGR_PSAVE);
        RTC.INTCTRL = RTC_OVERFLOW_INT_LEVEL;
        RTC.CTRL = CONFIG_RTC_PRESCALER;
}
void rtc_set_alarm (uint32_t time)
Set alarm time.
Will set absolute alarm time that will call the callback specifed by rtc_set_callback on completion. Or possibly use rtc_alarm_has_triggered to check for it.
Any pending alarm will be overwritten with this function.
Parameters:
time Absolute time value. See also Minimum allowed alarm time
Precondition:
Needs interrupts disabled if used from several contexts
Definition at line 135 of file rtc.c.
References rtc_data_struct::alarm_high, rtc_data_struct::alarm_low, RTC_COMPARE_INT_LEVEL, rtc_data, rtc_is_busy(), and RTC_OVERFLOW_INT_LEVEL.
Referenced by rtc_set_alarm_relative().
{
        RTC.INTCTRL = RTC_OVERFLOW_INT_LEVEL;
        while (rtc_is_busy());
        RTC.COMP = time;
        rtc_data.alarm_low = time;
        rtc_data.alarm_high = time >> 16;
        while (rtc_is_busy());
        RTC.INTCTRL = RTC_COMPARE_INT_LEVEL
                | RTC_OVERFLOW_INT_LEVEL;
}
static void rtc_set_alarm_relative (uint32_t offset) [inline, static]
Set alarm relative to current time.
Parameters:
offset Offset to current time. This is minimum value, so the alarm might happen at up to one time unit later. See also Minimum allowed alarm time
Note:
Due to errata, this can be unsafe to do shortly after waking up from sleep.
Definition at line 139 of file rtc.h.
References rtc_get_time(), and rtc_set_alarm().
{
        rtc_set_alarm(rtc_get_time() + offset);
}
void rtc_set_callback (rtc_callback_t callback)
Set callback to call on alarm.
Parameters:
callback Callback function pointer
Definition at line 164 of file rtc.c.
References rtc_data_struct::callback, and rtc_data.
{
        rtc_data.callback = callback;
}
void rtc_set_time (uint32_t time)
Set current time.
Parameters:
time Time value to set
Definition at line 90 of file rtc.c.
References rtc_data_struct::counter_high, rtc_data, and rtc_is_busy().
{
        RTC.CTRL = RTC_PRESCALER_OFF_gc;
        while (rtc_is_busy());
        RTC.CNT = time;
        rtc_data.counter_high = time >> 16;
        RTC.CTRL = CONFIG_RTC_PRESCALER;
}