@DOC_TITLE@
Xmega Application Note
ADC channel
[Analog to Digital Converter (ADC)]
Data Structures
struct adc_channel_config
ADC channel configuration.
Defines
#define CONFIG_ADC_INTLVL ADC_CH_INTLVL_LO_gc
Default ADC channel interrupt level.
Enumerations
enum adcch_mode { ADCCH_MODE_COMPLETE = ADC_CH_INTMODE_COMPLETE_gc, ADCCH_MODE_BELOW = ADC_CH_INTMODE_BELOW_gc, ADCCH_MODE_ABOVE = ADC_CH_INTMODE_ABOVE_gc }
ADC channel interrupt modes.
enum adcch_negative_input {
ADCCH_NEG_PIN0, ADCCH_NEG_PIN1, ADCCH_NEG_PIN2, ADCCH_NEG_PIN3,
ADCCH_NEG_PIN4, ADCCH_NEG_PIN5, ADCCH_NEG_PIN6, ADCCH_NEG_PIN7,
ADCCH_NEG_NONE
}
ADC channel negative input.
enum adcch_positive_input {
ADCCH_POS_PIN0, ADCCH_POS_PIN1, ADCCH_POS_PIN2, ADCCH_POS_PIN3,
ADCCH_POS_PIN4, ADCCH_POS_PIN5, ADCCH_POS_PIN6, ADCCH_POS_PIN7,
ADCCH_POS_TEMPSENSE, ADCCH_POS_BANDGAP, ADCCH_POS_SCALED_VCC
}
ADC channel positive input.
ADC channel configuration
static void adcch_disable_interrupt (struct adc_channel_config *ch_conf)
Disable interrupts on ADC channel.
static void adcch_enable_interrupt (struct adc_channel_config *ch_conf)
Enable interrupts on ADC channel.
static uint8_t adcch_get_gain_setting (uint8_t gain)
Get ADC channel setting for specified gain.
void adcch_read_configuration (ADC_t *adc, uint8_t ch, struct adc_channel_config *ch_conf)
Read configuration from ADC channel.
static void adcch_set_input (struct adc_channel_config *ch_conf, enum adcch_positive_input pos, enum adcch_negative_input neg, uint8_t gain)
Set ADC channel input mode, multiplexing and gain.
static void adcch_set_interrupt_mode (struct adc_channel_config *ch_conf, enum adcch_mode mode)
Set ADC channel interrupt mode.
void adcch_write_configuration (ADC_t *adc, uint8_t ch, const struct adc_channel_config *ch_conf)
Write configuration to ADC channel.
ADC channel management
static int16_t adcch_get_signed_result (ADC_t *adc, uint8_t ch)
Get signed result from ADC channel.
static uint16_t adcch_get_unsigned_result (ADC_t *adc, uint8_t ch)
Get unsigned result from ADC channel.
#define adcch_get_result(adc, ch) ((&(adc)->CH0 + ch)->RES)
Get result from ADC channel.
Detailed Description
Management and configuration functions for the individual ADC channels.
The API functions and definitions can be divided in two groups:
channel management: direct access for getting conversion result.
channel configuration: create/change configurations and write/read them to/from ADC channels.
Define Documentation
#define adcch_get_result (adc, ch) ((&(adc)->CH0 + ch)->RES)
Get result from ADC channel.
Gets the latest conversion result from the ADC channel.
Parameters:
adc Pointer to ADC module.
ch ADC channel number.
Returns:
Latest conversion result of ADC channel. Signedness does not matter.
Note:
This macro does not protect the 16-bit read from interrupts. If an interrupt may do a 16-bit read or write to the ADC while this macro is executing, interrupts must be temporarily disabled to avoid corruption of the read.
Definition at line 866 of file adc.h.
Referenced by main().
#define CONFIG_ADC_INTLVL ADC_CH_INTLVL_LO_gc
Default ADC channel interrupt level.
Note:
To override the channel interrupt level, define this symbol as the desired level in conf_intlvl.h.
Definition at line 753 of file adc.h.
Referenced by adcch_enable_interrupt().
Enumeration Type Documentation
enum adcch_mode
ADC channel interrupt modes.
Enumerator:
ADCCH_MODE_COMPLETE
Set interrupt flag when conversions complete.
ADCCH_MODE_BELOW
Set interrupt flag when conversion result is below compare value.
ADCCH_MODE_ABOVE
Set interrupt flag when conversion result is above compare value.
Definition at line 839 of file adc.h.
                {
        ADCCH_MODE_COMPLETE = ADC_CH_INTMODE_COMPLETE_gc,
        ADCCH_MODE_BELOW    = ADC_CH_INTMODE_BELOW_gc,
        ADCCH_MODE_ABOVE    = ADC_CH_INTMODE_ABOVE_gc,
};
enum adcch_negative_input
ADC channel negative input.
Identifies the external signals that can be used as negative input to the ADC channels in differential mode.
Note:
The ADC must be set in signed mode to use differential measurements. For single-ended measurements.
Enumerator:
ADCCH_NEG_PIN0
ADCCH_NEG_PIN1
ADCCH_NEG_PIN2
ADCCH_NEG_PIN3
ADCCH_NEG_PIN4
ADCCH_NEG_PIN5
ADCCH_NEG_PIN6
ADCCH_NEG_PIN7
ADCCH_NEG_NONE
Input for single-ended measurements.
Definition at line 818 of file adc.h.
{
        ADCCH_NEG_PIN0,
        ADCCH_NEG_PIN1,
        ADCCH_NEG_PIN2,
        ADCCH_NEG_PIN3,
        ADCCH_NEG_PIN4,
        ADCCH_NEG_PIN5,
        ADCCH_NEG_PIN6,
        ADCCH_NEG_PIN7,
        ADCCH_NEG_NONE,
};
enum adcch_positive_input
ADC channel positive input.
Identifies the external and internal signals that can be used as positive input to the ADC channels.
Note:
Not all devices can use pins on an alternate port. Refer to the device datasheet for information on the number of available ADC inputs.
Enumerator:
ADCCH_POS_PIN0
ADCCH_POS_PIN1
ADCCH_POS_PIN2
ADCCH_POS_PIN3
ADCCH_POS_PIN4
ADCCH_POS_PIN5
ADCCH_POS_PIN6
ADCCH_POS_PIN7
ADCCH_POS_TEMPSENSE
Temperature sensor.
ADCCH_POS_BANDGAP
Bandgap reference.
ADCCH_POS_SCALED_VCC
VCC scaled down by 10.
Definition at line 772 of file adc.h.
{
        ADCCH_POS_PIN0,
        ADCCH_POS_PIN1,
        ADCCH_POS_PIN2,
        ADCCH_POS_PIN3,
        ADCCH_POS_PIN4,
        ADCCH_POS_PIN5,
        ADCCH_POS_PIN6,
        ADCCH_POS_PIN7,
#if XMEGA_A4 || XMEGA_D
        ADCCH_POS_PIN8,
        ADCCH_POS_PIN9,
        ADCCH_POS_PIN10,
        ADCCH_POS_PIN11,
#endif
#if XMEGA_D3
        ADCCH_POS_PIN12,
        ADCCH_POS_PIN13,
        ADCCH_POS_PIN14,
        ADCCH_POS_PIN15,
#endif
        ADCCH_POS_TEMPSENSE,
        ADCCH_POS_BANDGAP,
        ADCCH_POS_SCALED_VCC,
#if XMEGA_A
        ADCCH_POS_DAC,
#endif
};
Function Documentation
static void adcch_disable_interrupt (struct adc_channel_config * ch_conf) [inline, static]
Disable interrupts on ADC channel.
Parameters:
ch_conf Pointer to ADC channel configuration.
Definition at line 1058 of file adc.h.
References adc_channel_config::intctrl.
Referenced by adc_ch3_callback().
{
        ch_conf->intctrl &= ~ADC_CH_INTLVL_gm;
        ch_conf->intctrl |= ADC_CH_INTLVL_OFF_gc;
}
static void adcch_enable_interrupt (struct adc_channel_config * ch_conf) [inline, static]
Enable interrupts on ADC channel.
Parameters:
ch_conf Pointer to ADC channel configuration.
Definition at line 1047 of file adc.h.
References CONFIG_ADC_INTLVL, and adc_channel_config::intctrl.
Referenced by main().
{
        ch_conf->intctrl &= ~ADC_CH_INTLVL_gm;
        ch_conf->intctrl |= CONFIG_ADC_INTLVL;
}
static uint8_t adcch_get_gain_setting (uint8_t gain) [inline, static]
Get ADC channel setting for specified gain.
For internal use only.
Returns the setting that corresponds to specified gain.
Parameters:
gain Valid gain factor for the measurement.
Returns:
Gain setting of type ADC_CH_GAIN_t.
Definition at line 940 of file adc.h.
References Assert.
Referenced by adcch_set_input().
{
        switch (gain) {
        case 1: return ADC_CH_GAIN_1X_gc;
        case 2: return ADC_CH_GAIN_2X_gc;
        case 4: return ADC_CH_GAIN_4X_gc;
        case 8: return ADC_CH_GAIN_8X_gc;
        case 16: return ADC_CH_GAIN_16X_gc;
        case 32: return ADC_CH_GAIN_32X_gc;
        case 64: return ADC_CH_GAIN_64X_gc;
        default:
                Assert(0);
                return 0;
        }
}
static int16_t adcch_get_signed_result (ADC_t * adc, uint8_t ch) [inline, static]
Get signed result from ADC channel.
Returns the latest conversion result from the ADC channel as a signed type, with interrupt protection of the 16-bit read.
Parameters:
adc Pointer to ADC module.
ch ADC channel number.
Returns:
Latest conversion result of ADC channel, as signed 16-bit integer.
Definition at line 879 of file adc.h.
References cpu_irq_restore(), and cpu_irq_save().
Referenced by adc_ch3_callback(), and main().
{
        int16_t    val;
        irqflags_t flags;
        ADC_CH_t   *adc_ch;
        adc_ch = &adc->CH0 + ch;
        flags = cpu_irq_save();
        val = adc_ch->RES;
        cpu_irq_restore(flags);
        return val;
}
static uint16_t adcch_get_unsigned_result (ADC_t * adc, uint8_t ch) [inline, static]
Get unsigned result from ADC channel.
Returns the latest conversion result from the ADC channel as an unsigned type, with interrupt protection of the 16-bit read.
Parameters:
adc Pointer to ADC module.
ch ADC channel number.
Returns:
Latest conversion result of ADC channel, as unsigned 16-bit integer.
Definition at line 905 of file adc.h.
References cpu_irq_restore(), and cpu_irq_save().
{
        uint16_t   val;
        irqflags_t flags;
        ADC_CH_t   *adc_ch;
        adc_ch = &adc->CH0 + ch;
        flags = cpu_irq_save();
        val = adc_ch->RES;
        cpu_irq_restore(flags);
        return val;
}
void adcch_read_configuration (ADC_t * adc, uint8_t ch, struct adc_channel_config * ch_conf)
Read configuration from ADC channel.
Reads out the current configuration from the ADC channel to the specified buffer.
Parameters:
adc Pointer to ADC module.
ch ADC channel number.
ch_conf Pointer to ADC channel configuration.
Definition at line 490 of file adc.c.
References adc_disable_clock(), adc_enable_clock(), Assert, cpu_irq_restore(), cpu_irq_save(), adc_channel_config::ctrl, adc_channel_config::intctrl, and adc_channel_config::muxctrl.
{
        ADC_CH_t *adc_ch;
        irqflags_t flags;
        Assert(ch < ADC_NR_OF_CHANNELS);
        adc_ch = &adc->CH0 + ch;
        flags = cpu_irq_save();
        adc_enable_clock(adc);
        ch_conf->ctrl = adc_ch->CTRL;
        ch_conf->intctrl = adc_ch->INTCTRL;
        ch_conf->muxctrl = adc_ch->MUXCTRL;
        adc_disable_clock(adc);
        cpu_irq_restore(flags);
}
static void adcch_set_input (struct adc_channel_config * ch_conf, enum adcch_positive_input pos, enum adcch_negative_input neg, uint8_t gain) [inline, static]
Set ADC channel input mode, multiplexing and gain.
Sets up an ADC channel's input mode and multiplexing according to specified input signals, as well as the gain.
Parameters:
ch_conf Pointer to ADC channel configuration.
pos Positive input signal.
neg Negative input signal:
ADCCH_NEG_NONE for single-ended measurements.
ADCCH_NEG_PINn , where n specifies a pin, for differential measurements.
gain Gain factor for measurements:
1 for single-ended or differential with pin 0, 1, 2 or 3 as negative input.
1, 2, 4, 8, 16, 32 or 64 for differential with pin 4, 5, 6 or 7 as negative input.
Definition at line 981 of file adc.h.
References adcch_get_gain_setting(), ADCCH_NEG_NONE, ADCCH_NEG_PIN4, ADCCH_POS_TEMPSENSE, Assert, adc_channel_config::ctrl, and adc_channel_config::muxctrl.
Referenced by main().
{
        Assert(gain);
        // Configure for internal input.
        if (pos >= ADCCH_POS_TEMPSENSE) {
                Assert(gain == 1);
                Assert(neg == ADCCH_NEG_NONE);
                ch_conf->ctrl = ADC_CH_INPUTMODE_INTERNAL_gc;
                ch_conf->muxctrl = (pos - ADCCH_POS_TEMPSENSE) <<
                                ADC_CH_MUXPOS_gp;
                return;
        }
        // Configure for single-ended measurement.
        if (neg == ADCCH_NEG_NONE) {
                Assert(gain == 1);
                ch_conf->ctrl = ADC_CH_INPUTMODE_SINGLEENDED_gc;
                ch_conf->muxctrl = pos << ADC_CH_MUXPOS_gp;
        // Configure for differential measurement.
        } else {
                /* Pins 0-3 can only be used for negative input if the gain
                 * stage is not used, i.e., unity gain.
                 */
                if (neg < ADCCH_NEG_PIN4) {
                        Assert(gain == 1);
                        ch_conf->ctrl = ADC_CH_INPUTMODE_DIFF_gc;
                        ch_conf->muxctrl = (pos << ADC_CH_MUXPOS_gp) |
                                        (neg << ADC_CH_MUXNEG_gp);
                } else {
                /* Pins 4-7 can be used for all gain settings, including unity
                 * gain, which is available even if the gain stage is active.
                 */
                        ch_conf->ctrl = ADC_CH_INPUTMODE_DIFFWGAIN_gc |
                                        adcch_get_gain_setting(gain);
                        ch_conf->muxctrl = (pos << ADC_CH_MUXPOS_gp) |
                                        ((neg - ADCCH_NEG_PIN4) <<
                                        ADC_CH_MUXNEG_gp);
                }
        }
}
static void adcch_set_interrupt_mode (struct adc_channel_config * ch_conf, enum adcch_mode mode) [inline, static]
Set ADC channel interrupt mode.
Parameters:
ch_conf Pointer to ADC channel configuration.
mode Interrupt mode to set.
Definition at line 1035 of file adc.h.
References adc_channel_config::intctrl.
Referenced by main().
{
        ch_conf->intctrl &= ~ADC_CH_INTMODE_gm;
        ch_conf->intctrl |= mode;
}
void adcch_write_configuration (ADC_t * adc, uint8_t ch, const struct adc_channel_config * ch_conf)
Write configuration to ADC channel.
Writes the specified configuration to the ADC channel.
Parameters:
adc Pointer to ADC module.
ch ADC channel number.
ch_conf Pointer to ADC channel configuration.
Note:
The specified ADC's callback function must be set before this function is called if callbacks are enabled and interrupts are enabled in the channel configuration.
Definition at line 439 of file adc.c.
References adc_disable_clock(), adc_enable_clock(), Assert, cpu_irq_restore(), cpu_irq_save(), adc_channel_config::ctrl, adc_channel_config::intctrl, and adc_channel_config::muxctrl.
Referenced by adc_ch3_callback(), and main().
{
        ADC_CH_t   *adc_ch;
        irqflags_t flags;
        Assert(ch < ADC_NR_OF_CHANNELS);
        adc_ch = &adc->CH0 + ch;
        flags = cpu_irq_save();
#if defined(CONFIG_ADC_CALLBACK_ENABLE) && defined(_ASSERT_ENABLE_)
        if ((adc_ch->INTCTRL & ADC_CH_INTLVL_gm) != ADC_CH_INTLVL_OFF_gc) {
#ifdef ADCA
                if ((uintptr_t)adc == (uintptr_t)&ADCA) {
                        Assert(adca_callback);
                } else
#endif /* ADCA */
#ifdef ADCB
                if ((uintptr_t)adc == (uintptr_t)&ADCB) {
                        Assert(adcb_callback);
                } else
#endif /* ADCB */
                {
                        Assert(0);
                        return;
                }
        }
#endif /* CONFIG_ADC_CALLBACK_ENABLE */
        adc_enable_clock(adc);
        adc_ch->CTRL = ch_conf->ctrl;
        adc_ch->INTCTRL = ch_conf->intctrl;
        adc_ch->MUXCTRL = ch_conf->muxctrl;
        adc_disable_clock(adc);
        cpu_irq_restore(flags);
}