@DOC_TITLE@
Xmega Application Note
ADC module
[Analog to Digital Converter (ADC)]
Data Structures
struct adc_config
ADC configuration.
Enumerations
enum adc_calibration_data { ADC_CAL_ADCA, ADC_CAL_ADCB, ADC_CAL_TEMPSENSE }
ADC calibration data.
enum adc_reference { ADC_REF_BANDGAP = ADC_REFSEL_INT1V_gc, ADC_REF_VCC = ADC_REFSEL_VCC_gc, ADC_REF_AREFA = ADC_REFSEL_AREFA_gc, ADC_REF_AREFB = ADC_REFSEL_AREFB_gc }
ADC reference settings.
enum adc_resolution { ADC_RES_8 = ADC_RESOLUTION_8BIT_gc, ADC_RES_12 = ADC_RESOLUTION_12BIT_gc, ADC_RES_12_LEFT = ADC_RESOLUTION_LEFT12BIT_gc }
ADC resolution settings.
enum adc_sign { ADC_SIGN_OFF, ADC_SIGN_ON = ADC_CONMODE_bm }
ADC signedness settings.
enum adc_trigger { ADC_TRIG_MANUAL, ADC_TRIG_FREERUN_SWEEP, ADC_TRIG_EVENT_SINGLE }
ADC conversion trigger settings.
ADC module management
static void adc_clear_interrupt_flag (ADC_t *adc, uint8_t ch_mask)
Clear interrupt flag of ADC channel(s).
void adc_disable (ADC_t *adc)
Disable ADC.
void adc_enable (ADC_t *adc)
Enable ADC.
static void adc_flush (ADC_t *adc)
Flush the ADC.
static uint16_t adc_get_calibration_data (enum adc_calibration_data cal)
Get calibration data.
static uint8_t adc_get_interrupt_flag (ADC_t *adc, uint8_t ch_mask)
Get interrupt flag of ADC channel(s).
static int16_t adc_get_signed_compare_value (ADC_t *adc)
Get signed compare value directly from ADC.
static uint16_t adc_get_unsigned_compare_value (ADC_t *adc)
Get unsigned compare value directly from ADC.
bool adc_is_enabled (ADC_t *adc)
Check if the ADC is enabled.
static void adc_start_conversion (ADC_t *adc, uint8_t ch_mask)
Start one-shot conversion on ADC channel(s).
static void adc_wait_for_interrupt_flag (ADC_t *adc, uint8_t ch_mask)
Wait for interrupt flag of ADC channel(s).
#define adc_get_compare_value(adc) ((adc)->CMP)
Get compare value directly from ADC.
#define adc_set_compare_value(adc, val)
Set compare value directly to ADC.
ADC module configuration
static void adc_disable_internal_input (struct adc_config *conf, uint8_t int_inp)
Disable internal ADC input.
static void adc_enable_internal_input (struct adc_config *conf, uint8_t int_inp)
Enable internal ADC input.
void adc_read_configuration (ADC_t *adc, struct adc_config *conf)
Read configuration from ADC module.
static void adc_set_clock_rate (struct adc_config *conf, uint32_t clk_adc)
Set ADC prescaler to get desired clock rate.
static void adc_set_conversion_parameters (struct adc_config *conf, enum adc_sign sign, enum adc_resolution res, enum adc_reference ref)
Set ADC conversion parameters.
static void adc_set_conversion_trigger (struct adc_config *conf, enum adc_trigger trig, uint8_t nr_of_ch, uint8_t base_ev_ch)
Set ADC conversion trigger.
void adc_write_configuration (ADC_t *adc, const struct adc_config *conf)
Write configuration to ADC module.
#define adc_get_config_compare_value(conf) (conf->cmp)
Get ADC compare value from configuration.
#define adc_set_config_compare_value(conf, val)
Set ADC compare value in configuration.
ADC channel masks
#define ADC_CH0 (1U << 0)
ADC channel 0.
Internal ADC input masks
#define ADC_INT_BANDGAP ADC_BANDGAP_bm
Bandgap reference.
#define ADC_INT_TEMPSENSE ADC_TEMPREF_bm
Temperature sensor.
Calibration data addresses
Note:
The temperature sensor calibration is sampled at 85 degrees Celsius with unsigned, 12-bit conversion.
#define ADCACAL0 offsetof(NVM_PROD_SIGNATURES_t, ADCACAL0)
ADC A, calibration byte 0.
#define ADCACAL1 offsetof(NVM_PROD_SIGNATURES_t, ADCACAL1)
ADC A, calibration byte 1.
#define ADCBCAL0 offsetof(NVM_PROD_SIGNATURES_t, ADCBCAL0)
ADC B, calibration byte 0.
#define ADCBCAL1 offsetof(NVM_PROD_SIGNATURES_t, ADCBCAL1)
ADC B, calibration byte 1.
#define TEMPSENSE0 offsetof(NVM_PROD_SIGNATURES_t, TEMPSENSE0)
Temperature sensor calibration byte 0.
#define TEMPSENSE1 offsetof(NVM_PROD_SIGNATURES_t, TEMPSENSE1)
Temperature sensor calibration byte 1.
Detailed Description
Management and configuration functions for the ADC module.
The API functions and definitions can be divided in three groups:
interrupt callback: configure and set interrupt callback function.
module management: direct access for enabling and disabling the ADC, starting conversions, getting interrupt flags, etc.
module configuration: create/change configurations and write/read them to/from an ADC.
Define Documentation
#define ADC_CH0 (1U << 0)
ADC channel 0.
Definition at line 158 of file adc.h.
Referenced by main().
#define adc_get_compare_value (adc) ((adc)->CMP)
Get compare value directly from ADC.
Gets the compare value directly from the ADC, for quick access while the ADC is enabled.
Parameters:
adc Pointer to ADC module.
Returns:
Current compare value of the ADC. Signedness does not matter.
Note:
This macro does not protect the 16-bit read from interrupts. If an interrupt may do a 16-bit read or write to the ADC while this macro is executing, interrupts must be temporarily disabled to avoid corruption of the read.
Definition at line 416 of file adc.h.
#define adc_get_config_compare_value (conf) (conf->cmp)
Get ADC compare value from configuration.
Parameters:
conf Pointer to ADC module configuration.
Definition at line 727 of file adc.h.
#define ADC_INT_BANDGAP ADC_BANDGAP_bm
Bandgap reference.
Definition at line 172 of file adc.h.
#define ADC_INT_TEMPSENSE ADC_TEMPREF_bm
Temperature sensor.
Definition at line 171 of file adc.h.
#define adc_set_compare_value (adc, val)
Value:
do {                                                                   \
                irqflags_t ATPASTE2(adc_flags, __LINE__) =  cpu_irq_save();    \
                (adc)->CMP = val;                                              \
                cpu_irq_restore(ATPASTE2(adc_flags, __LINE__));                \
        } while (0)
Set compare value directly to ADC.
Sets the compare value directly to the ADC, for quick access while the ADC is enabled.
Parameters:
adc Pointer to ADC module.
val Compare value to set, either signed or unsigned.
Note:
The ADC must be enabled for this function to have any effect.
Definition at line 394 of file adc.h.
#define adc_set_config_compare_value (conf, val)
Value:
do {                                       \
                conf->cmp = (uint16_t)val;         \
        } while (0)
Set ADC compare value in configuration.
Parameters:
conf Pointer to ADC module configuration.
val Compare value to set.
Definition at line 717 of file adc.h.
#define ADCACAL0 offsetof(NVM_PROD_SIGNATURES_t, ADCACAL0)
ADC A, calibration byte 0.
Definition at line 129 of file adc.h.
Referenced by adc_get_calibration_data().
#define ADCACAL1 offsetof(NVM_PROD_SIGNATURES_t, ADCACAL1)
ADC A, calibration byte 1.
Definition at line 131 of file adc.h.
Referenced by adc_get_calibration_data().
#define ADCBCAL0 offsetof(NVM_PROD_SIGNATURES_t, ADCBCAL0)
ADC B, calibration byte 0.
Definition at line 133 of file adc.h.
Referenced by adc_get_calibration_data().
#define ADCBCAL1 offsetof(NVM_PROD_SIGNATURES_t, ADCBCAL1)
ADC B, calibration byte 1.
Definition at line 135 of file adc.h.
Referenced by adc_get_calibration_data().
#define TEMPSENSE0 offsetof(NVM_PROD_SIGNATURES_t, TEMPSENSE0)
Temperature sensor calibration byte 0.
Definition at line 137 of file adc.h.
Referenced by adc_get_calibration_data().
#define TEMPSENSE1 offsetof(NVM_PROD_SIGNATURES_t, TEMPSENSE1)
Temperature sensor calibration byte 1.
Definition at line 139 of file adc.h.
Referenced by adc_get_calibration_data().
Enumeration Type Documentation
enum adc_calibration_data
ADC calibration data.
Enumerator:
ADC_CAL_ADCA
ADC A pipeline calibration data.
ADC_CAL_ADCB
ADC B pipeline calibration data.
ADC_CAL_TEMPSENSE
Temperature sensor calibration data.
Note:
12-bit unsigned, measured at 85 degrees Celsius, equivalent to 358.15 kelvin.
Definition at line 144 of file adc.h.
{
        ADC_CAL_ADCA,
        ADC_CAL_ADCB,
        ADC_CAL_TEMPSENSE,
};
enum adc_reference
ADC reference settings.
Enumerator:
ADC_REF_BANDGAP
Internal 1 V from bandgap reference.
ADC_REF_VCC
VCC divided by 1.6.
ADC_REF_AREFA
External reference on AREFA pin.
ADC_REF_AREFB
External reference on AREFB pin.
Definition at line 228 of file adc.h.
                   {
        ADC_REF_BANDGAP = ADC_REFSEL_INT1V_gc,
        ADC_REF_VCC     = ADC_REFSEL_VCC_gc,
        ADC_REF_AREFA   = ADC_REFSEL_AREFA_gc,
        ADC_REF_AREFB   = ADC_REFSEL_AREFB_gc,
};
enum adc_resolution
ADC resolution settings.
Enumerator:
ADC_RES_8
8-bit resolution, right-adjusted.
ADC_RES_12
12-bit resolution, right-adjusted.
ADC_RES_12_LEFT
12-bit resolution, left-adjusted.
Definition at line 218 of file adc.h.
                    {
        ADC_RES_8       = ADC_RESOLUTION_8BIT_gc,
        ADC_RES_12      = ADC_RESOLUTION_12BIT_gc,
        ADC_RES_12_LEFT = ADC_RESOLUTION_LEFT12BIT_gc,
};
enum adc_sign
ADC signedness settings.
Enumerator:
ADC_SIGN_OFF
Unsigned conversions.
ADC_SIGN_ON
Signed conversions.
Definition at line 212 of file adc.h.
              {
        ADC_SIGN_OFF,
        ADC_SIGN_ON = ADC_CONMODE_bm,
};
enum adc_trigger
ADC conversion trigger settings.
Note:
The choice in conversion triggers varies between device families. Refer to the device manual for detailed information.
Enumerator:
ADC_TRIG_MANUAL
Manually triggered conversions.
ADC_TRIG_FREERUN_SWEEP
Freerunning conversion sweeps.
Note:
These will start as soon as the ADC is enabled.
ADC_TRIG_EVENT_SINGLE
Event-triggered conversions on individual channels Pairs each event channel with an ADC channel.
Note:
The maximum base event channel that can be used is determined by the number of channels to trigger conversions on.
Definition at line 182 of file adc.h.
                 {
        ADC_TRIG_MANUAL,
        ADC_TRIG_FREERUN_SWEEP,
        ADC_TRIG_EVENT_SINGLE,
#if XMEGA_A
        ADC_TRIG_EVENT_SWEEP,
        ADC_TRIG_EVENT_SYNCSWEEP,
#endif
};
Function Documentation
static void adc_clear_interrupt_flag (ADC_t * adc, uint8_t ch_mask) [inline, static]
Clear interrupt flag of ADC channel(s).
Parameters:
adc Pointer to ADC module.
ch_mask Mask of ADC channel(s):
ADC_CHn , where n specifies the channel. (These can be OR'ed together.)
Note:
The ADC must be enabled for this function to have any effect.
Definition at line 342 of file adc.h.
Referenced by adc_wait_for_interrupt_flag().
{
        adc->INTFLAGS = ch_mask << ADC_CH0IF_bp;
}
void adc_disable (ADC_t * adc)
Disable ADC.
Disables the ADC and unlocks IDLE mode for the sleep manager.
Parameters:
adc Pointer to ADC module
Definition at line 296 of file adc.c.
References adc_disable_clock(), cpu_irq_restore(), cpu_irq_save(), SLEEPMGR_IDLE, and sleepmgr_unlock_mode().
Referenced by adc_ch3_callback(), and main().
{
        irqflags_t flags = cpu_irq_save();
        adc->CTRLA &= ~ADC_ENABLE_bm;
        adc_disable_clock(adc);
        cpu_irq_restore(flags);
        sleepmgr_unlock_mode(SLEEPMGR_IDLE);
}
static void adc_disable_internal_input (struct adc_config * conf, uint8_t int_inp) [inline, static]
Disable internal ADC input.
Parameters:
conf Pointer to ADC module configuration.
int_inp Internal input to disable:
ADC_INT_TEMPSENSE for temperature sensor.
ADC_INT_BANDGAP for bandgap reference.
Definition at line 705 of file adc.h.
References adc_config::refctrl.
{
        conf->refctrl &= ~int_inp;
}
void adc_enable (ADC_t * adc)
Enable ADC.
Enables the ADC and locks IDLE mode for the sleep manager.
Parameters:
adc Pointer to ADC module
Note:
After enabling the ADC, one dummy conversion should be done to allow for its common mode voltage to settle.
Definition at line 279 of file adc.c.
References adc_enable_clock(), cpu_irq_restore(), cpu_irq_save(), SLEEPMGR_IDLE, and sleepmgr_lock_mode().
Referenced by main().
{
        irqflags_t flags = cpu_irq_save();
        adc_enable_clock(adc);
        adc->CTRLA |= ADC_ENABLE_bm;
        cpu_irq_restore(flags);
        sleepmgr_lock_mode(SLEEPMGR_IDLE);
}
static void adc_enable_internal_input (struct adc_config * conf, uint8_t int_inp) [inline, static]
Enable internal ADC input.
Parameters:
conf Pointer to ADC module configuration.
int_inp Internal input to enable:
ADC_INT_TEMPSENSE for temperature sensor.
ADC_INT_BANDGAP for bandgap reference.
Definition at line 691 of file adc.h.
References adc_config::refctrl.
{
        conf->refctrl |= int_inp;
}
static void adc_flush (ADC_t * adc) [inline, static]
Flush the ADC.
Forces the ADC to abort any ongoing conversions and restart its clock on the next peripheral clock cycle. Pending conversions are started after the clock reset.
Parameters:
adc Pointer to ADC module.
Note:
The ADC must be enabled for this function to have any effect.
Definition at line 376 of file adc.h.
References cpu_irq_restore(), and cpu_irq_save().
{
        irqflags_t flags = cpu_irq_save();
        adc->CTRLA |= ADC_FLUSH_bm;
        cpu_irq_restore(flags);
}
static uint16_t adc_get_calibration_data (enum adc_calibration_data cal) [inline, static]
Get calibration data.
Parameters:
cal Identifier for calibration data to get.
Definition at line 463 of file adc.h.
References ADC_CAL_ADCA, ADC_CAL_ADCB, ADC_CAL_TEMPSENSE, ADCACAL0, ADCACAL1, ADCBCAL0, ADCBCAL1, Assert, nvm_read_production_signature_row(), TEMPSENSE0, and TEMPSENSE1.
Referenced by adc_write_configuration(), and main().
{
        uint16_t data;
        switch (cal) {
#ifdef ADCA
        case ADC_CAL_ADCA:
                data = nvm_read_production_signature_row(ADCACAL1);
                data <<= 8;
                data |= nvm_read_production_signature_row(ADCACAL0);
                break;
#endif
#ifdef ADCB
        case ADC_CAL_ADCB:
                data = nvm_read_production_signature_row(ADCBCAL1);
                data <<= 8;
                data |= nvm_read_production_signature_row(ADCBCAL0);
                break;
#endif
#if defined(ADCA) || defined(ADCB)
        case ADC_CAL_TEMPSENSE:
                data = nvm_read_production_signature_row(TEMPSENSE1);
                data <<= 8;
                data |= nvm_read_production_signature_row(TEMPSENSE0);
                break;
#endif
        default:
                Assert(0);
                data = 0;
        }
        return data;
}
static uint8_t adc_get_interrupt_flag (ADC_t * adc, uint8_t ch_mask) [inline, static]
Get interrupt flag of ADC channel(s).
Returns the interrupt flag of the masked channels. The meaning of the interrupt flag depends on what mode the individual channels are in.
Parameters:
adc Pointer to ADC module.
ch_mask Mask of ADC channel(s):
ADC_CHn , where n specifies the channel. (These can be OR'ed together.)
Returns:
Mask with interrupt flags.
Definition at line 327 of file adc.h.
Referenced by adc_wait_for_interrupt_flag().
{
        return (adc->INTFLAGS >> ADC_CH0IF_bp) & ch_mask;
}
static int16_t adc_get_signed_compare_value (ADC_t * adc) [inline, static]
Get signed compare value directly from ADC.
Gets the signed compare value directly from the ADC, with interrupt protection of the 16-bit read, for quick access while the ADC is enabled.
Parameters:
adc Pointer to ADC module.
Definition at line 426 of file adc.h.
References cpu_irq_restore(), and cpu_irq_save().
{
        int16_t val;
        irqflags_t flags;
        flags = cpu_irq_save();
        val = adc->CMP;
        cpu_irq_restore(flags);
        return val;
}
static uint16_t adc_get_unsigned_compare_value (ADC_t * adc) [inline, static]
Get unsigned compare value directly from ADC.
Gets the unsigned compare value directly from the ADC, with interrupt protection of the 16-bit read, for quick access while the ADC is enabled.
Parameters:
adc Pointer to ADC module.
Definition at line 446 of file adc.h.
References cpu_irq_restore(), and cpu_irq_save().
{
        uint16_t val;
        irqflags_t flags;
        flags = cpu_irq_save();
        val = adc->CMP;
        cpu_irq_restore(flags);
        return val;
}
bool adc_is_enabled (ADC_t * adc)
Check if the ADC is enabled.
Parameters:
adc Pointer to ADC module.
Return values:
true if ADC is enabled.
false if ADC is disabled.
Definition at line 314 of file adc.c.
References Assert.
{
        /* It is sufficient to return the state of the ADC enable counters
         * since all driver functions that change the counts are protected
         * against interrupts and only the enable/disable functions leave the
         * counts incremented/decremented upon return.
         */
#ifdef ADCA
        if ((uintptr_t)adc == (uintptr_t)&ADCA) {
                return adca_enable_count;
        } else
#endif
#ifdef ADCB
        if ((uintptr_t)adc == (uintptr_t)&ADCB) {
                return adcb_enable_count;
        } else
#endif
        {
                Assert(0);
                return false;
        }
}
void adc_read_configuration (ADC_t * adc, struct adc_config * conf)
Read configuration from ADC module.
Reads out the current configuration of the ADC module to the specified buffer.
Parameters:
adc Pointer to ADC module.
conf Pointer to ADC module configuration.
Definition at line 405 of file adc.c.
References adc_disable_clock(), adc_enable_clock(), adc_config::cmp, cpu_irq_restore(), cpu_irq_save(), adc_config::ctrlb, adc_config::evctrl, adc_config::prescaler, and adc_config::refctrl.
{
        irqflags_t flags = cpu_irq_save();
        adc_enable_clock(adc);
#if XMEGA_A
        conf->ctrla = adc->CTRLA & ADC_DMASEL_gm;
#endif
        conf->cmp = adc->CMP;
        conf->refctrl = adc->REFCTRL;
        conf->prescaler = adc->PRESCALER;
        conf->evctrl = adc->EVCTRL;
        conf->ctrlb = adc->CTRLB;
        adc_disable_clock(adc);
        cpu_irq_restore(flags);
}
static void adc_set_clock_rate (struct adc_config * conf, uint32_t clk_adc) [inline, static]
Set ADC prescaler to get desired clock rate.
Sets the ADC prescaling so that its clock rate becomes _at most_ clk_adc_hz. This is done by computing the ratio of the peripheral clock rate to the desired ADC clock rate, and rounding it upward to the nearest prescaling factor.
Parameters:
conf Pointer to ADC module configuration.
clk_adc Desired ADC clock rate.
Note:
The sample rate is not determined solely by the ADC clock rate for all devices. Refer to the device manual for detailed information on conversion timing.
Definition at line 523 of file adc.h.
References Assert, adc_config::prescaler, and sysclk_get_per_hz().
Referenced by main().
{
        uint32_t clk_per;
        uint16_t ratio;
        uint8_t  psc;
        Assert(clk_adc);
#if XMEGA_A
        Assert(clk_adc <= 2000000UL);
#elif XMEGA_D
        Assert(clk_adc <= 1400000UL);
#endif
        clk_per = sysclk_get_per_hz();
        ratio = clk_per / clk_adc;
        // Round ratio up to the nearest prescaling factor.
        if(ratio <= 4) {
                psc = ADC_PRESCALER_DIV4_gc;
        } else if (ratio <= 8) {
                psc = ADC_PRESCALER_DIV8_gc;
        } else if (ratio <= 16) {
                psc = ADC_PRESCALER_DIV16_gc;
        } else if (ratio <= 32) {
                psc = ADC_PRESCALER_DIV32_gc;
        } else if (ratio <= 64) {
                psc = ADC_PRESCALER_DIV64_gc;
        } else if (ratio <= 128) {
                psc = ADC_PRESCALER_DIV128_gc;
        } else if (ratio <= 256) {
                psc = ADC_PRESCALER_DIV256_gc;
        } else {
                psc = ADC_PRESCALER_DIV512_gc;
        }
        conf->prescaler = psc;
}
static void adc_set_conversion_parameters (struct adc_config * conf, enum adc_sign sign, enum adc_resolution res, enum adc_reference ref) [inline, static]
Set ADC conversion parameters.
Sets the signedness, resolution and voltage reference for conversions in the ADC module configuration.
Parameters:
conf Pointer to ADC module configuration.
sign Conversion signedness.
res Resolution of conversions.
ref Voltage reference to use.
Definition at line 572 of file adc.h.
References adc_config::ctrlb, and adc_config::refctrl.
Referenced by main().
{
        // Preserve all but conversion and resolution config.
        conf->ctrlb &= ~(ADC_CONMODE_bm | ADC_RESOLUTION_gm);
        conf->ctrlb |= (uint8_t)res | (uint8_t)sign;
        conf->refctrl &= ~ADC_REFSEL_gm;
        conf->refctrl |= ref;
}
static void adc_set_conversion_trigger (struct adc_config * conf, enum adc_trigger trig, uint8_t nr_of_ch, uint8_t base_ev_ch) [inline, static]
Set ADC conversion trigger.
Configures the conversion triggering of the ADC.
For automatic triggering modes, the number of channels to start conversions on must be specified with nr_of_ch. The channel selection for these modes is incrementally inclusive, always starting with channel 0.
For event triggered modes, the base event channel must also be specified with base_ev_ch. The event channels are assigned to the ADC channels in an incremental fashion without wrap-around (in single-trigger event mode). This means that the maximum base event channel that can be used is determined by the number of ADC channels to start conversions on, i.e., nr_of_ch.
Parameters:
conf Pointer to ADC module configuration.
trig Conversion trigger to set.
nr_of_ch Number of ADC channels to trigger conversions on:
1 - ADC_NR_OF_CHANNELS (must be non-zero).
base_ev_ch Base event channel, if used.
Definition at line 605 of file adc.h.
References ADC_TRIG_EVENT_SINGLE, ADC_TRIG_FREERUN_SWEEP, ADC_TRIG_MANUAL, Assert, adc_config::ctrlb, and adc_config::evctrl.
Referenced by adc_ch3_callback(), and main().
{
        Assert(nr_of_ch);
        Assert(nr_of_ch <= ADC_NR_OF_CHANNELS);
#if XMEGA_A
        Assert(base_ev_ch <= 7);
#elif XMEGA_D
        Assert(base_ev_ch <= 3);
#endif
        switch (trig) {
        case ADC_TRIG_MANUAL:
                conf->ctrlb &= ~ADC_FREERUN_bm;
                conf->evctrl = ADC_EVACT_NONE_gc;
                break;
        case ADC_TRIG_FREERUN_SWEEP:
                conf->ctrlb |= ADC_FREERUN_bm;
                conf->evctrl = (nr_of_ch - 1) << ADC_SWEEP_gp;
                break;
        case ADC_TRIG_EVENT_SINGLE:
                conf->ctrlb &= ~ADC_FREERUN_bm;
                conf->evctrl = (base_ev_ch << ADC_EVSEL_gp) |
                                (nr_of_ch << ADC_EVACT_gp);
                break;
#if XMEGA_A
        case ADC_TRIG_EVENT_SWEEP:
                conf->ctrlb &= ~ADC_FREERUN_bm;
                conf->evctrl = (nr_of_ch - 1) << ADC_SWEEP_gp |
                                (base_ev_ch << ADC_EVSEL_gp) |
                                ADC_EVACT_SWEEP_gc;
                break;
        case ADC_TRIG_EVENT_SYNCSWEEP:
                conf->ctrlb &= ~ADC_FREERUN_bm;
                conf->evctrl = ((nr_of_ch - 1) << ADC_SWEEP_gp) |
                                (base_ev_ch << ADC_EVSEL_gp) |
                                ADC_EVACT_SYNCHSWEEP_gc;
                break;
#endif
        default:
                Assert(0);
        }
}
static void adc_start_conversion (ADC_t * adc, uint8_t ch_mask) [inline, static]
Start one-shot conversion on ADC channel(s).
Parameters:
adc Pointer to ADC module.
ch_mask Mask of ADC channel(s):
ADC_CHn , where n specifies the channel. (These can be OR'ed together.)
Note:
The ADC must be enabled for this function to have any effect.
Definition at line 307 of file adc.h.
References cpu_irq_restore(), and cpu_irq_save().
Referenced by main().
{
        irqflags_t flags = cpu_irq_save();
        adc->CTRLA |= ch_mask << ADC_CH0START_bp;
        cpu_irq_restore(flags);
}
static void adc_wait_for_interrupt_flag (ADC_t * adc, uint8_t ch_mask) [inline, static]
Wait for interrupt flag of ADC channel(s).
Waits for the interrupt flag of the specified channel(s) to be set, then clears it before returning. If several channels are masked, the function will wait for all interrupt flags to be set.
Parameters:
adc Pointer to ADC module.
ch_mask Mask of ADC channel(s):
ADC_CHn , where n specifies the channel. (These can be OR'ed together.)
Definition at line 359 of file adc.h.
References adc_clear_interrupt_flag(), and adc_get_interrupt_flag().
Referenced by main().
{
        do { } while (adc_get_interrupt_flag(adc, ch_mask) != ch_mask);
        adc_clear_interrupt_flag(adc, ch_mask);
}
void adc_write_configuration (ADC_t * adc, const struct adc_config * conf)
Write configuration to ADC module.
Disables the ADC and flushes its pipeline before writing the specified configuration and factory calibration value to it. If the ADC was enabled upon entry of the function, it is enabled upon function return.
Parameters:
adc Pointer to ADC module.
conf Pointer to ADC module configuration.
Definition at line 349 of file adc.c.
References ADC_CAL_ADCA, ADC_CAL_ADCB, adc_disable_clock(), adc_enable_clock(), adc_get_calibration_data(), Assert, adc_config::cmp, cpu_irq_restore(), cpu_irq_save(), adc_config::ctrlb, adc_config::evctrl, adc_config::prescaler, and adc_config::refctrl.
Referenced by adc_ch3_callback(), and main().
{
        uint16_t cal;
        uint8_t  enable;
        irqflags_t flags;
#ifdef ADCA
        if ((uintptr_t)adc == (uintptr_t)&ADCA) {
                cal = adc_get_calibration_data(ADC_CAL_ADCA);
        } else
#endif
#ifdef ADCB
        if ((uintptr_t)adc == (uintptr_t)&ADCB) {
                cal = adc_get_calibration_data(ADC_CAL_ADCB);
        } else
#endif
        {
                Assert(0);
                return;
        }
        flags = cpu_irq_save();
        adc_enable_clock(adc);
        enable = adc->CTRLA & ADC_ENABLE_bm;
        adc->CTRLA = ADC_FLUSH_bm;
        adc->CAL = cal;
        adc->CMP = conf->cmp;
        adc->REFCTRL = conf->refctrl;
        adc->PRESCALER = conf->prescaler;
        adc->EVCTRL = conf->evctrl;
        adc->CTRLB = conf->ctrlb;
#if XMEGA_A
        adc->CTRLA = enable | conf->ctrla;
#elif XMEGA_D
        adc->CTRLA = enable;
#endif
        adc_disable_clock(adc);
        cpu_irq_restore(flags);
}