@DOC_TITLE@
Xmega Application Note
usart_example_interrupt.c File Reference
Detailed Description
XMEGA USART interrupt driven driver example source.
This file contains an example application that demonstrates the interrupt driven USART driver. The code example sends three bytes, waits for three bytes to be received and tests if the received data equals the sent data.
Application note:
AVR1307: Using the XMEGA USART
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
1694
Date
2008-07-29 14:21:58 +0200 (ti, 29 jul 2008)
Copyright (c) 2008, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file usart_example_interrupt.c.
#include "usart_driver.h"
#include "avr_compiler.h"
Defines
#define NUM_BYTES 3
#define USART USARTC0
Functions
ISR (USARTC0_DRE_vect)
Data register empty interrupt service routine.
ISR (USARTC0_RXC_vect)
Receive complete interrupt service routine.
int main (void)
Example application.
Variables
uint8_t receiveArray [NUM_BYTES]
uint8_t sendArray [NUM_BYTES] = {0x55, 0xaa, 0xf0}
bool success
USART_data_t USART_data
Define Documentation
#define NUM_BYTES 3
Number of bytes to send in test example.
Definition at line 55 of file usart_example_interrupt.c.
Referenced by main().
#define USART USARTC0
Define that selects the Usart used in example.
Definition at line 57 of file usart_example_interrupt.c.
Referenced by main().
Function Documentation
ISR (USARTC0_DRE_vect)
Data register empty interrupt service routine.
Data register empty interrupt service routine. Calls the common data register empty complete handler with pointer to the correct USART as argument.
Definition at line 179 of file usart_example_interrupt.c.
References USART_DataRegEmpty().
{
        USART_DataRegEmpty(&USART_data);
}
ISR (USARTC0_RXC_vect)
Receive complete interrupt service routine.
Receive complete interrupt service routine. Calls the common receive complete handler with pointer to the correct USART as argument.
Definition at line 167 of file usart_example_interrupt.c.
References USART_RXComplete().
{
        USART_RXComplete(&USART_data);
}
int main (void)
Example application.
Example application. This example configures USARTC0 for with the parameters:
8 bit character size
No parity
1 stop bit
9600 Baud
This function then sends three bytes and tests if the received data is equal to the sent data. The code can be tested by connecting PC3 to PC2. If the variable 'success' is true at the end of the function, the three bytes have been successfully sent and received.
Definition at line 82 of file usart_example_interrupt.c.
References NUM_BYTES, receiveArray, sendArray, success, Usart_and_buffer::usart, USART, USART_Baudrate_Set, USART_Format_Set, USART_InterruptDriver_Initialize(), USART_Rx_Enable, USART_RXBuffer_GetByte(), USART_RXBufferData_Available(), USART_RxdInterruptLevel_Set, USART_Tx_Enable, and USART_TXBuffer_PutByte().
{
        /* counter variable. */
        uint8_t i;
        /* This PORT setting is only valid to USARTC0 if other USARTs is used a
         * different PORT and/or pins are used. */
        /* PC3 (TXD0) as output. */
        PORTC.DIRSET   = PIN3_bm;
        /* PC2 (RXD0) as input. */
        PORTC.DIRCLR   = PIN2_bm;
        /* Use USARTC0 and initialize buffers. */
        USART_InterruptDriver_Initialize(&USART_data, &USART, USART_DREINTLVL_LO_gc);
        /* USARTC0, 8 Data bits, No Parity, 1 Stop bit. */
        USART_Format_Set(USART_data.usart, USART_CHSIZE_8BIT_gc,
                     USART_PMODE_DISABLED_gc, false);
        /* Enable RXC interrupt. */
        USART_RxdInterruptLevel_Set(USART_data.usart, USART_RXCINTLVL_LO_gc);
        /* Set Baudrate to 9600 bps:
         * Use the default I/O clock frequency that is 2 MHz.
         * Do not use the baudrate scale factor
         *
         * Baudrate select = (1/(16*(((I/O clock frequency)/Baudrate)-1)
         *                 = 12
         */
        USART_Baudrate_Set(&USART, 12 , 0);
        /* Enable both RX and TX. */
        USART_Rx_Enable(USART_data.usart);
        USART_Tx_Enable(USART_data.usart);
        /* Enable PMIC interrupt level low. */
        PMIC.CTRL |= PMIC_LOLVLEX_bm;
        /* Enable global interrupts. */
        sei();
        /* Send sendArray. */
        i = 0;
        while (i < NUM_BYTES) {
                bool byteToBuffer;
                byteToBuffer = USART_TXBuffer_PutByte(&USART_data, sendArray[i]);
                if(byteToBuffer){
                        i++;
                }
        }
        /* Fetch received data as it is received. */
        i = 0;
        while (i < NUM_BYTES) {
                if (USART_RXBufferData_Available(&USART_data)) {
                        receiveArray[i] = USART_RXBuffer_GetByte(&USART_data);
                        i++;
                }
        }
        /* Test to see if sent data equals received data. */
        /* Assume success first.*/
        success = true;
        for(i = 0; i < NUM_BYTES; i++) {
                /* Check that each element is received correctly. */
                if (receiveArray[i] != sendArray[i]) {
                        success = false;
                }
        }
        /* If success the program ends up inside the if statement.*/
        if(success){
                while(true);
        }else{
                while(true);
        }
}
Variable Documentation
uint8_t receiveArray[NUM_BYTES]
Array to put received data in.
Definition at line 64 of file usart_example_interrupt.c.
Referenced by main().
uint8_t sendArray[NUM_BYTES] = {0x55, 0xaa, 0xf0}
Test data to send.
Definition at line 62 of file usart_example_interrupt.c.
Referenced by main().
bool success
Success variable, used to test driver.
Definition at line 66 of file usart_example_interrupt.c.
Referenced by main().
USART_data_t USART_data
USART data struct used in example.
Definition at line 60 of file usart_example_interrupt.c.