"""autogenerated by genpy from osuar_telepilot/altitude_command.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class altitude_command(genpy.Message):
  _md5sum = "38309b3fa0e56a6c3a3648261c145959"
  _type = "osuar_telepilot/altitude_command"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 throttle_little
int16 throttle_big
char status

"""
  __slots__ = ['throttle_little','throttle_big','status']
  _slot_types = ['int16','int16','char']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       throttle_little,throttle_big,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(altitude_command, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.throttle_little is None:
        self.throttle_little = 0
      if self.throttle_big is None:
        self.throttle_big = 0
      if self.status is None:
        self.status = 0
    else:
      self.throttle_little = 0
      self.throttle_big = 0
      self.status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2hB.pack(_x.throttle_little, _x.throttle_big, _x.status))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.throttle_little, _x.throttle_big, _x.status,) = _struct_2hB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2hB.pack(_x.throttle_little, _x.throttle_big, _x.status))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.throttle_little, _x.throttle_big, _x.status,) = _struct_2hB.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2hB = struct.Struct("<2hB")
